-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sha256_core is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    data_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    data_in_TVALID : IN STD_LOGIC;
    data_in_TREADY : OUT STD_LOGIC;
    data_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    data_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    data_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    hash_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    hash_out_TVALID : OUT STD_LOGIC;
    hash_out_TREADY : IN STD_LOGIC;
    hash_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    hash_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    hash_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of sha256_core is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sha256_core,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.996000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=5937,HLS_SYN_LUT=2940,HLS_VERSION=2019_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv36_0 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000000";
    constant ap_const_lv32_5BE0CD19 : STD_LOGIC_VECTOR (31 downto 0) := "01011011111000001100110100011001";
    constant ap_const_lv32_1F83D9AB : STD_LOGIC_VECTOR (31 downto 0) := "00011111100000111101100110101011";
    constant ap_const_lv32_9B05688C : STD_LOGIC_VECTOR (31 downto 0) := "10011011000001010110100010001100";
    constant ap_const_lv32_510E527F : STD_LOGIC_VECTOR (31 downto 0) := "01010001000011100101001001111111";
    constant ap_const_lv32_A54FF53A : STD_LOGIC_VECTOR (31 downto 0) := "10100101010011111111010100111010";
    constant ap_const_lv32_3C6EF372 : STD_LOGIC_VECTOR (31 downto 0) := "00111100011011101111001101110010";
    constant ap_const_lv32_BB67AE85 : STD_LOGIC_VECTOR (31 downto 0) := "10111011011001111010111010000101";
    constant ap_const_lv32_6A09E667 : STD_LOGIC_VECTOR (31 downto 0) := "01101010000010011110011001100111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv36_1 : STD_LOGIC_VECTOR (35 downto 0) := "000000000000000000000000000000000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal data_in_V_data_V_0_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal data_in_V_data_V_0_vld_in : STD_LOGIC;
    signal data_in_V_data_V_0_vld_out : STD_LOGIC;
    signal data_in_V_data_V_0_ack_in : STD_LOGIC;
    signal data_in_V_data_V_0_ack_out : STD_LOGIC;
    signal data_in_V_data_V_0_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal data_in_V_data_V_0_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal data_in_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal data_in_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal data_in_V_data_V_0_sel : STD_LOGIC;
    signal data_in_V_data_V_0_load_A : STD_LOGIC;
    signal data_in_V_data_V_0_load_B : STD_LOGIC;
    signal data_in_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal data_in_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal data_in_V_last_V_0_vld_in : STD_LOGIC;
    signal data_in_V_last_V_0_ack_out : STD_LOGIC;
    signal data_in_V_last_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal hash_out_V_data_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal hash_out_V_data_V_1_vld_in : STD_LOGIC;
    signal hash_out_V_data_V_1_vld_out : STD_LOGIC;
    signal hash_out_V_data_V_1_ack_in : STD_LOGIC;
    signal hash_out_V_data_V_1_ack_out : STD_LOGIC;
    signal hash_out_V_data_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal hash_out_V_data_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal hash_out_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal hash_out_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal hash_out_V_data_V_1_sel : STD_LOGIC;
    signal hash_out_V_data_V_1_load_A : STD_LOGIC;
    signal hash_out_V_data_V_1_load_B : STD_LOGIC;
    signal hash_out_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal hash_out_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal hash_out_V_keep_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal hash_out_V_keep_V_1_vld_in : STD_LOGIC;
    signal hash_out_V_keep_V_1_vld_out : STD_LOGIC;
    signal hash_out_V_keep_V_1_ack_out : STD_LOGIC;
    signal hash_out_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal hash_out_V_keep_V_1_sel : STD_LOGIC;
    signal hash_out_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal hash_out_V_strb_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal hash_out_V_strb_V_1_vld_in : STD_LOGIC;
    signal hash_out_V_strb_V_1_vld_out : STD_LOGIC;
    signal hash_out_V_strb_V_1_ack_out : STD_LOGIC;
    signal hash_out_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal hash_out_V_strb_V_1_sel : STD_LOGIC;
    signal hash_out_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal hash_out_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal hash_out_V_last_V_1_vld_in : STD_LOGIC;
    signal hash_out_V_last_V_1_vld_out : STD_LOGIC;
    signal hash_out_V_last_V_1_ack_in : STD_LOGIC;
    signal hash_out_V_last_V_1_ack_out : STD_LOGIC;
    signal hash_out_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal hash_out_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal hash_out_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal hash_out_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal hash_out_V_last_V_1_sel : STD_LOGIC;
    signal hash_out_V_last_V_1_load_A : STD_LOGIC;
    signal hash_out_V_last_V_1_load_B : STD_LOGIC;
    signal hash_out_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal hash_out_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal num_blocks : STD_LOGIC_VECTOR (31 downto 0);
    signal data_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln73_reg_900 : STD_LOGIC_VECTOR (0 downto 0);
    signal hash_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln83_reg_1002 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal icmp_ln83_reg_1002_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i1_0_reg_348 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_397_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal tmp_reg_815 : STD_LOGIC_VECTOR (35 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln73_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln73_fu_474_p2 : STD_LOGIC_VECTOR (35 downto 0);
    signal add_ln73_reg_904 : STD_LOGIC_VECTOR (35 downto 0);
    signal state_0_V_reg_909 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3 : BOOLEAN;
    signal grp_sha256_transform_fu_359_ap_ready : STD_LOGIC;
    signal grp_sha256_transform_fu_359_ap_done : STD_LOGIC;
    signal state_1_V_reg_914 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_2_V_reg_919 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_3_V_reg_924 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_4_V_reg_929 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_5_V_reg_934 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_6_V_reg_939 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_7_V_reg_944 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln75_fu_518_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln75_reg_949 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln73_fu_526_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_reg_954 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_1_fu_534_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_1_reg_959 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_2_fu_542_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_2_reg_964 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_3_fu_550_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_3_reg_969 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_4_fu_558_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_4_reg_974 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_5_fu_566_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_5_reg_979 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_6_fu_574_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_6_reg_984 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_7_fu_582_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln73_7_reg_989 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_fu_678_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln83_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_3_fu_689_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal out_word_data_V_fu_699_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_word_data_V_reg_1011 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_word_last_V_fu_713_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_word_last_V_reg_1016 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state5 : STD_LOGIC;
    signal grp_sha256_transform_fu_359_ap_start : STD_LOGIC;
    signal grp_sha256_transform_fu_359_ap_idle : STD_LOGIC;
    signal grp_sha256_transform_fu_359_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_sha256_transform_fu_359_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal indvar_flatten_reg_230 : STD_LOGIC_VECTOR (35 downto 0);
    signal state_7_V_0_reg_241 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_6_V_0_reg_253 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_5_V_0_reg_265 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_4_V_0_reg_277 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_3_V_0_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_2_V_0_reg_301 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_1_V_0_reg_313 : STD_LOGIC_VECTOR (31 downto 0);
    signal state_0_V_0_reg_325 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_337 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sha256_transform_fu_359_ap_start_reg : STD_LOGIC := '0';
    signal tmp_data_V_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln321_fu_594_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_data_V_1_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_2_fu_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_3_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_4_fu_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_5_fu_150 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_6_fu_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_7_fu_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_8_fu_162 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_9_fu_166 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_10_fu_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_11_fu_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_12_fu_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_13_fu_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_14_fu_186 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_15_fu_190 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln75_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_word_data_V_fu_699_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_block_state8 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component sha256_transform IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        state_0_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_1_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_2_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_3_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_4_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_5_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_6_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        state_7_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_0_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_1_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_2_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_3_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_4_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_5_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_6_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_7_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_8_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_9_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_10_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_11_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_12_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_13_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_14_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        block_15_V_read : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_core_mux_8dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component sha256_core_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        num_blocks : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    sha256_core_CTRL_s_axi_U : component sha256_core_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        num_blocks => num_blocks);

    grp_sha256_transform_fu_359 : component sha256_transform
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_sha256_transform_fu_359_ap_start,
        ap_done => grp_sha256_transform_fu_359_ap_done,
        ap_idle => grp_sha256_transform_fu_359_ap_idle,
        ap_ready => grp_sha256_transform_fu_359_ap_ready,
        state_0_V_read => state_0_V_0_reg_325,
        state_1_V_read => state_1_V_0_reg_313,
        state_2_V_read => state_2_V_0_reg_301,
        state_3_V_read => state_3_V_0_reg_289,
        state_4_V_read => state_4_V_0_reg_277,
        state_5_V_read => state_5_V_0_reg_265,
        state_6_V_read => state_6_V_0_reg_253,
        state_7_V_read => state_7_V_0_reg_241,
        block_0_V_read => tmp_data_V_fu_130,
        block_1_V_read => tmp_data_V_1_fu_134,
        block_2_V_read => tmp_data_V_2_fu_138,
        block_3_V_read => tmp_data_V_3_fu_142,
        block_4_V_read => tmp_data_V_4_fu_146,
        block_5_V_read => tmp_data_V_5_fu_150,
        block_6_V_read => tmp_data_V_6_fu_154,
        block_7_V_read => tmp_data_V_7_fu_158,
        block_8_V_read => tmp_data_V_8_fu_162,
        block_9_V_read => tmp_data_V_9_fu_166,
        block_10_V_read => tmp_data_V_10_fu_170,
        block_11_V_read => tmp_data_V_11_fu_174,
        block_12_V_read => tmp_data_V_12_fu_178,
        block_13_V_read => tmp_data_V_13_fu_182,
        block_14_V_read => tmp_data_V_14_fu_186,
        block_15_V_read => tmp_data_V_15_fu_190,
        ap_return_0 => grp_sha256_transform_fu_359_ap_return_0,
        ap_return_1 => grp_sha256_transform_fu_359_ap_return_1,
        ap_return_2 => grp_sha256_transform_fu_359_ap_return_2,
        ap_return_3 => grp_sha256_transform_fu_359_ap_return_3,
        ap_return_4 => grp_sha256_transform_fu_359_ap_return_4,
        ap_return_5 => grp_sha256_transform_fu_359_ap_return_5,
        ap_return_6 => grp_sha256_transform_fu_359_ap_return_6,
        ap_return_7 => grp_sha256_transform_fu_359_ap_return_7);

    sha256_core_mux_8dEe_U37 : component sha256_core_mux_8dEe
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 3,
        dout_WIDTH => 32)
    port map (
        din0 => state_0_V_reg_909,
        din1 => state_1_V_reg_914,
        din2 => state_2_V_reg_919,
        din3 => state_3_V_reg_924,
        din4 => state_4_V_reg_929,
        din5 => state_5_V_reg_934,
        din6 => state_6_V_reg_939,
        din7 => state_7_V_reg_944,
        din8 => out_word_data_V_fu_699_p9,
        dout => out_word_data_V_fu_699_p10);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state5)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state5);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    data_in_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                data_in_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((data_in_V_data_V_0_ack_out = ap_const_logic_1) and (data_in_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        data_in_V_data_V_0_sel_rd <= not(data_in_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    data_in_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                data_in_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((data_in_V_data_V_0_ack_in = ap_const_logic_1) and (data_in_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        data_in_V_data_V_0_sel_wr <= not(data_in_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    data_in_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                data_in_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((data_in_V_data_V_0_state = ap_const_lv2_2) and (data_in_V_data_V_0_vld_in = ap_const_logic_0)) or ((data_in_V_data_V_0_state = ap_const_lv2_3) and (data_in_V_data_V_0_vld_in = ap_const_logic_0) and (data_in_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    data_in_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((data_in_V_data_V_0_state = ap_const_lv2_1) and (data_in_V_data_V_0_ack_out = ap_const_logic_0)) or ((data_in_V_data_V_0_state = ap_const_lv2_3) and (data_in_V_data_V_0_ack_out = ap_const_logic_0) and (data_in_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    data_in_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((data_in_V_data_V_0_vld_in = ap_const_logic_0) and (data_in_V_data_V_0_ack_out = ap_const_logic_1))) and not(((data_in_V_data_V_0_ack_out = ap_const_logic_0) and (data_in_V_data_V_0_vld_in = ap_const_logic_1))) and (data_in_V_data_V_0_state = ap_const_lv2_3)) or ((data_in_V_data_V_0_state = ap_const_lv2_1) and (data_in_V_data_V_0_ack_out = ap_const_logic_1)) or ((data_in_V_data_V_0_state = ap_const_lv2_2) and (data_in_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    data_in_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    data_in_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    data_in_V_last_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                data_in_V_last_V_0_state <= ap_const_lv2_0;
            else
                if ((((data_in_V_last_V_0_state = ap_const_lv2_2) and (data_in_V_last_V_0_vld_in = ap_const_logic_0)) or ((data_in_V_last_V_0_state = ap_const_lv2_3) and (data_in_V_last_V_0_vld_in = ap_const_logic_0) and (data_in_V_last_V_0_ack_out = ap_const_logic_1)))) then 
                    data_in_V_last_V_0_state <= ap_const_lv2_2;
                elsif ((((data_in_V_last_V_0_state = ap_const_lv2_1) and (data_in_V_last_V_0_ack_out = ap_const_logic_0)) or ((data_in_V_last_V_0_state = ap_const_lv2_3) and (data_in_V_last_V_0_ack_out = ap_const_logic_0) and (data_in_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    data_in_V_last_V_0_state <= ap_const_lv2_1;
                elsif (((not(((data_in_V_last_V_0_vld_in = ap_const_logic_0) and (data_in_V_last_V_0_ack_out = ap_const_logic_1))) and not(((data_in_V_last_V_0_ack_out = ap_const_logic_0) and (data_in_V_last_V_0_vld_in = ap_const_logic_1))) and (data_in_V_last_V_0_state = ap_const_lv2_3)) or ((data_in_V_last_V_0_state = ap_const_lv2_1) and (data_in_V_last_V_0_ack_out = ap_const_logic_1)) or ((data_in_V_last_V_0_state = ap_const_lv2_2) and (data_in_V_last_V_0_vld_in = ap_const_logic_1)))) then 
                    data_in_V_last_V_0_state <= ap_const_lv2_3;
                else 
                    data_in_V_last_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    grp_sha256_transform_fu_359_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_sha256_transform_fu_359_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_sha256_transform_fu_359_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sha256_transform_fu_359_ap_ready = ap_const_logic_1)) then 
                    grp_sha256_transform_fu_359_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((hash_out_V_data_V_1_ack_out = ap_const_logic_1) and (hash_out_V_data_V_1_vld_out = ap_const_logic_1))) then 
                                        hash_out_V_data_V_1_sel_rd <= not(hash_out_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((hash_out_V_data_V_1_ack_in = ap_const_logic_1) and (hash_out_V_data_V_1_vld_in = ap_const_logic_1))) then 
                                        hash_out_V_data_V_1_sel_wr <= not(hash_out_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((hash_out_V_data_V_1_state = ap_const_lv2_2) and (hash_out_V_data_V_1_vld_in = ap_const_logic_0)) or ((hash_out_V_data_V_1_state = ap_const_lv2_3) and (hash_out_V_data_V_1_vld_in = ap_const_logic_0) and (hash_out_V_data_V_1_ack_out = ap_const_logic_1)))) then 
                    hash_out_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((hash_out_V_data_V_1_state = ap_const_lv2_1) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_data_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0) and (hash_out_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((hash_out_V_data_V_1_vld_in = ap_const_logic_0) and (hash_out_V_data_V_1_ack_out = ap_const_logic_1))) and not(((hash_out_TREADY = ap_const_logic_0) and (hash_out_V_data_V_1_vld_in = ap_const_logic_1))) and (hash_out_V_data_V_1_state = ap_const_lv2_3)) or ((hash_out_V_data_V_1_state = ap_const_lv2_1) and (hash_out_V_data_V_1_ack_out = ap_const_logic_1)) or ((hash_out_V_data_V_1_state = ap_const_lv2_2) and (hash_out_V_data_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    hash_out_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((hash_out_V_keep_V_1_ack_out = ap_const_logic_1) and (hash_out_V_keep_V_1_vld_out = ap_const_logic_1))) then 
                                        hash_out_V_keep_V_1_sel_rd <= not(hash_out_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((hash_out_V_keep_V_1_state = ap_const_lv2_2) and (hash_out_V_keep_V_1_vld_in = ap_const_logic_0)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_3) and (hash_out_V_keep_V_1_vld_in = ap_const_logic_0) and (hash_out_V_keep_V_1_ack_out = ap_const_logic_1)))) then 
                    hash_out_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((hash_out_V_keep_V_1_state = ap_const_lv2_1) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0) and (hash_out_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((hash_out_V_keep_V_1_vld_in = ap_const_logic_0) and (hash_out_V_keep_V_1_ack_out = ap_const_logic_1))) and not(((hash_out_TREADY = ap_const_logic_0) and (hash_out_V_keep_V_1_vld_in = ap_const_logic_1))) and (hash_out_V_keep_V_1_state = ap_const_lv2_3)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_1) and (hash_out_V_keep_V_1_ack_out = ap_const_logic_1)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_2) and (hash_out_V_keep_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    hash_out_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((hash_out_V_last_V_1_ack_out = ap_const_logic_1) and (hash_out_V_last_V_1_vld_out = ap_const_logic_1))) then 
                                        hash_out_V_last_V_1_sel_rd <= not(hash_out_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((hash_out_V_last_V_1_ack_in = ap_const_logic_1) and (hash_out_V_last_V_1_vld_in = ap_const_logic_1))) then 
                                        hash_out_V_last_V_1_sel_wr <= not(hash_out_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((hash_out_V_last_V_1_state = ap_const_lv2_2) and (hash_out_V_last_V_1_vld_in = ap_const_logic_0)) or ((hash_out_V_last_V_1_state = ap_const_lv2_3) and (hash_out_V_last_V_1_vld_in = ap_const_logic_0) and (hash_out_V_last_V_1_ack_out = ap_const_logic_1)))) then 
                    hash_out_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((hash_out_V_last_V_1_state = ap_const_lv2_1) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_last_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0) and (hash_out_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((hash_out_V_last_V_1_vld_in = ap_const_logic_0) and (hash_out_V_last_V_1_ack_out = ap_const_logic_1))) and not(((hash_out_TREADY = ap_const_logic_0) and (hash_out_V_last_V_1_vld_in = ap_const_logic_1))) and (hash_out_V_last_V_1_state = ap_const_lv2_3)) or ((hash_out_V_last_V_1_state = ap_const_lv2_1) and (hash_out_V_last_V_1_ack_out = ap_const_logic_1)) or ((hash_out_V_last_V_1_state = ap_const_lv2_2) and (hash_out_V_last_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    hash_out_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((hash_out_V_strb_V_1_ack_out = ap_const_logic_1) and (hash_out_V_strb_V_1_vld_out = ap_const_logic_1))) then 
                                        hash_out_V_strb_V_1_sel_rd <= not(hash_out_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    hash_out_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                hash_out_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((hash_out_V_strb_V_1_state = ap_const_lv2_2) and (hash_out_V_strb_V_1_vld_in = ap_const_logic_0)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_3) and (hash_out_V_strb_V_1_vld_in = ap_const_logic_0) and (hash_out_V_strb_V_1_ack_out = ap_const_logic_1)))) then 
                    hash_out_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((hash_out_V_strb_V_1_state = ap_const_lv2_1) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0) and (hash_out_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_strb_V_1_state <= ap_const_lv2_1;
                elsif (((not(((hash_out_V_strb_V_1_vld_in = ap_const_logic_0) and (hash_out_V_strb_V_1_ack_out = ap_const_logic_1))) and not(((hash_out_TREADY = ap_const_logic_0) and (hash_out_V_strb_V_1_vld_in = ap_const_logic_1))) and (hash_out_V_strb_V_1_state = ap_const_lv2_3)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_1) and (hash_out_V_strb_V_1_ack_out = ap_const_logic_1)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_2) and (hash_out_V_strb_V_1_vld_in = ap_const_logic_1)))) then 
                    hash_out_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    hash_out_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_348_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i1_0_reg_348 <= ap_const_lv4_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln83_fu_683_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i1_0_reg_348 <= i_3_fu_689_p2;
            end if; 
        end if;
    end process;

    i_0_reg_337_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                i_0_reg_337 <= i_fu_678_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_337 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_230_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                indvar_flatten_reg_230 <= add_ln73_reg_904;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_reg_230 <= ap_const_lv36_0;
            end if; 
        end if;
    end process;

    state_0_V_0_reg_325_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_0_V_0_reg_325 <= select_ln73_7_reg_989;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_0_V_0_reg_325 <= ap_const_lv32_6A09E667;
            end if; 
        end if;
    end process;

    state_1_V_0_reg_313_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_1_V_0_reg_313 <= select_ln73_6_reg_984;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_1_V_0_reg_313 <= ap_const_lv32_BB67AE85;
            end if; 
        end if;
    end process;

    state_2_V_0_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_2_V_0_reg_301 <= select_ln73_5_reg_979;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_2_V_0_reg_301 <= ap_const_lv32_3C6EF372;
            end if; 
        end if;
    end process;

    state_3_V_0_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_3_V_0_reg_289 <= select_ln73_4_reg_974;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_3_V_0_reg_289 <= ap_const_lv32_A54FF53A;
            end if; 
        end if;
    end process;

    state_4_V_0_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_4_V_0_reg_277 <= select_ln73_3_reg_969;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_4_V_0_reg_277 <= ap_const_lv32_510E527F;
            end if; 
        end if;
    end process;

    state_5_V_0_reg_265_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_5_V_0_reg_265 <= select_ln73_2_reg_964;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_5_V_0_reg_265 <= ap_const_lv32_9B05688C;
            end if; 
        end if;
    end process;

    state_6_V_0_reg_253_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_6_V_0_reg_253 <= select_ln73_1_reg_959;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_6_V_0_reg_253 <= ap_const_lv32_1F83D9AB;
            end if; 
        end if;
    end process;

    state_7_V_0_reg_241_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                state_7_V_0_reg_241 <= select_ln73_reg_954;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                state_7_V_0_reg_241 <= ap_const_lv32_5BE0CD19;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln73_reg_904 <= add_ln73_fu_474_p2;
                icmp_ln73_reg_900 <= icmp_ln73_fu_469_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((data_in_V_data_V_0_load_A = ap_const_logic_1)) then
                data_in_V_data_V_0_payload_A <= data_in_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((data_in_V_data_V_0_load_B = ap_const_logic_1)) then
                data_in_V_data_V_0_payload_B <= data_in_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((hash_out_V_data_V_1_load_A = ap_const_logic_1)) then
                hash_out_V_data_V_1_payload_A <= out_word_data_V_reg_1011;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((hash_out_V_data_V_1_load_B = ap_const_logic_1)) then
                hash_out_V_data_V_1_payload_B <= out_word_data_V_reg_1011;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((hash_out_V_last_V_1_load_A = ap_const_logic_1)) then
                hash_out_V_last_V_1_payload_A <= out_word_last_V_reg_1016;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((hash_out_V_last_V_1_load_B = ap_const_logic_1)) then
                hash_out_V_last_V_1_payload_B <= out_word_last_V_reg_1016;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln83_reg_1002 <= icmp_ln83_fu_683_p2;
                icmp_ln83_reg_1002_pp0_iter1_reg <= icmp_ln83_reg_1002;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln83_fu_683_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                out_word_data_V_reg_1011 <= out_word_data_V_fu_699_p10;
                out_word_last_V_reg_1016 <= out_word_last_V_fu_713_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                select_ln73_1_reg_959 <= select_ln73_1_fu_534_p3;
                select_ln73_2_reg_964 <= select_ln73_2_fu_542_p3;
                select_ln73_3_reg_969 <= select_ln73_3_fu_550_p3;
                select_ln73_4_reg_974 <= select_ln73_4_fu_558_p3;
                select_ln73_5_reg_979 <= select_ln73_5_fu_566_p3;
                select_ln73_6_reg_984 <= select_ln73_6_fu_574_p3;
                select_ln73_7_reg_989 <= select_ln73_7_fu_582_p3;
                select_ln73_reg_954 <= select_ln73_fu_526_p3;
                select_ln75_reg_949 <= select_ln75_fu_518_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                state_0_V_reg_909 <= grp_sha256_transform_fu_359_ap_return_0;
                state_1_V_reg_914 <= grp_sha256_transform_fu_359_ap_return_1;
                state_2_V_reg_919 <= grp_sha256_transform_fu_359_ap_return_2;
                state_3_V_reg_924 <= grp_sha256_transform_fu_359_ap_return_3;
                state_4_V_reg_929 <= grp_sha256_transform_fu_359_ap_return_4;
                state_5_V_reg_934 <= grp_sha256_transform_fu_359_ap_return_5;
                state_6_V_reg_939 <= grp_sha256_transform_fu_359_ap_return_6;
                state_7_V_reg_944 <= grp_sha256_transform_fu_359_ap_return_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_A) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_10_fu_170 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_B) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_11_fu_174 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_C) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_12_fu_178 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_D) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_13_fu_182 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_E) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_14_fu_186 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_F) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_15_fu_190 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_1) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_1_fu_134 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_2) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_2_fu_138 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_3) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_3_fu_142 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_4) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_4_fu_146 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_5) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_5_fu_150 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_6) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_6_fu_154 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_7) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_7_fu_158 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_8) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_8_fu_162 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_9) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_9_fu_166 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (trunc_ln321_fu_594_p1 = ap_const_lv4_0) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                tmp_data_V_fu_130 <= data_in_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    tmp_reg_815(35 downto 4) <= tmp_fu_397_p3(35 downto 4);
            end if;
        end if;
    end process;
    tmp_reg_815(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, data_in_V_data_V_0_vld_out, hash_out_TREADY, hash_out_V_data_V_1_state, hash_out_V_keep_V_1_state, hash_out_V_strb_V_1_state, hash_out_V_last_V_1_state, ap_CS_fsm_state3, icmp_ln73_reg_900, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, grp_sha256_transform_fu_359_ap_done, icmp_ln83_fu_683_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln83_fu_683_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln83_fu_683_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not(((hash_out_V_last_V_1_state = ap_const_lv2_1) or (hash_out_V_strb_V_1_state = ap_const_lv2_1) or (hash_out_V_keep_V_1_state = ap_const_lv2_1) or (hash_out_V_data_V_1_state = ap_const_lv2_1) or ((hash_out_V_last_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_data_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln73_fu_474_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_230) + unsigned(ap_const_lv36_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state8 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_io, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state6_io, ap_block_state7_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state7_io) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state6_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state3_assign_proc : process(data_in_V_data_V_0_vld_out, icmp_ln73_reg_900)
    begin
                ap_block_state3 <= ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0));
    end process;

        ap_block_state5_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state6_io_assign_proc : process(hash_out_V_data_V_1_ack_in, icmp_ln83_reg_1002)
    begin
                ap_block_state6_io <= ((icmp_ln83_reg_1002 = ap_const_lv1_0) and (hash_out_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state6_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_io_assign_proc : process(hash_out_V_data_V_1_ack_in, icmp_ln83_reg_1002_pp0_iter1_reg)
    begin
                ap_block_state7_io <= ((icmp_ln83_reg_1002_pp0_iter1_reg = ap_const_lv1_0) and (hash_out_V_data_V_1_ack_in = ap_const_logic_0));
    end process;

        ap_block_state7_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_assign_proc : process(hash_out_TREADY, hash_out_V_data_V_1_state, hash_out_V_keep_V_1_state, hash_out_V_strb_V_1_state, hash_out_V_last_V_1_state)
    begin
                ap_block_state8 <= ((hash_out_V_last_V_1_state = ap_const_lv2_1) or (hash_out_V_strb_V_1_state = ap_const_lv2_1) or (hash_out_V_keep_V_1_state = ap_const_lv2_1) or (hash_out_V_data_V_1_state = ap_const_lv2_1) or ((hash_out_V_last_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_data_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state5_assign_proc : process(icmp_ln83_fu_683_p2)
    begin
        if ((icmp_ln83_fu_683_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(hash_out_TREADY, hash_out_V_data_V_1_state, hash_out_V_keep_V_1_state, hash_out_V_strb_V_1_state, hash_out_V_last_V_1_state, ap_CS_fsm_state8)
    begin
        if ((not(((hash_out_V_last_V_1_state = ap_const_lv2_1) or (hash_out_V_strb_V_1_state = ap_const_lv2_1) or (hash_out_V_keep_V_1_state = ap_const_lv2_1) or (hash_out_V_data_V_1_state = ap_const_lv2_1) or ((hash_out_V_last_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_data_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(hash_out_TREADY, hash_out_V_data_V_1_state, hash_out_V_keep_V_1_state, hash_out_V_strb_V_1_state, hash_out_V_last_V_1_state, ap_CS_fsm_state8)
    begin
        if ((not(((hash_out_V_last_V_1_state = ap_const_lv2_1) or (hash_out_V_strb_V_1_state = ap_const_lv2_1) or (hash_out_V_keep_V_1_state = ap_const_lv2_1) or (hash_out_V_data_V_1_state = ap_const_lv2_1) or ((hash_out_V_last_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_strb_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_keep_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)) or ((hash_out_V_data_V_1_state = ap_const_lv2_3) and (hash_out_TREADY = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    data_in_TDATA_blk_n_assign_proc : process(data_in_V_data_V_0_state, ap_CS_fsm_state3, icmp_ln73_reg_900)
    begin
        if (((icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_in_TDATA_blk_n <= data_in_V_data_V_0_state(0);
        else 
            data_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    data_in_TREADY <= data_in_V_last_V_0_state(1);
    data_in_V_data_V_0_ack_in <= data_in_V_data_V_0_state(1);

    data_in_V_data_V_0_ack_out_assign_proc : process(data_in_V_data_V_0_vld_out, ap_CS_fsm_state3, icmp_ln73_reg_900, grp_sha256_transform_fu_359_ap_done)
    begin
        if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_in_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            data_in_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    data_in_V_data_V_0_data_out_assign_proc : process(data_in_V_data_V_0_payload_A, data_in_V_data_V_0_payload_B, data_in_V_data_V_0_sel)
    begin
        if ((data_in_V_data_V_0_sel = ap_const_logic_1)) then 
            data_in_V_data_V_0_data_out <= data_in_V_data_V_0_payload_B;
        else 
            data_in_V_data_V_0_data_out <= data_in_V_data_V_0_payload_A;
        end if; 
    end process;

    data_in_V_data_V_0_load_A <= (not(data_in_V_data_V_0_sel_wr) and data_in_V_data_V_0_state_cmp_full);
    data_in_V_data_V_0_load_B <= (data_in_V_data_V_0_state_cmp_full and data_in_V_data_V_0_sel_wr);
    data_in_V_data_V_0_sel <= data_in_V_data_V_0_sel_rd;
    data_in_V_data_V_0_state_cmp_full <= '0' when (data_in_V_data_V_0_state = ap_const_lv2_1) else '1';
    data_in_V_data_V_0_vld_in <= data_in_TVALID;
    data_in_V_data_V_0_vld_out <= data_in_V_data_V_0_state(0);

    data_in_V_last_V_0_ack_out_assign_proc : process(data_in_V_data_V_0_vld_out, ap_CS_fsm_state3, icmp_ln73_reg_900, grp_sha256_transform_fu_359_ap_done)
    begin
        if ((not(((grp_sha256_transform_fu_359_ap_done = ap_const_logic_0) or ((icmp_ln73_reg_900 = ap_const_lv1_0) and (data_in_V_data_V_0_vld_out = ap_const_logic_0)))) and (icmp_ln73_reg_900 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_in_V_last_V_0_ack_out <= ap_const_logic_1;
        else 
            data_in_V_last_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    data_in_V_last_V_0_vld_in <= data_in_TVALID;
    grp_sha256_transform_fu_359_ap_start <= grp_sha256_transform_fu_359_ap_start_reg;
    hash_out_TDATA <= hash_out_V_data_V_1_data_out;

    hash_out_TDATA_blk_n_assign_proc : process(hash_out_V_data_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln83_reg_1002, ap_enable_reg_pp0_iter2, icmp_ln83_reg_1002_pp0_iter1_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln83_reg_1002_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln83_reg_1002 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            hash_out_TDATA_blk_n <= hash_out_V_data_V_1_state(1);
        else 
            hash_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    hash_out_TKEEP <= hash_out_V_keep_V_1_data_out;
    hash_out_TLAST <= hash_out_V_last_V_1_data_out;
    hash_out_TSTRB <= hash_out_V_strb_V_1_data_out;
    hash_out_TVALID <= hash_out_V_last_V_1_state(0);
    hash_out_V_data_V_1_ack_in <= hash_out_V_data_V_1_state(1);
    hash_out_V_data_V_1_ack_out <= hash_out_TREADY;

    hash_out_V_data_V_1_data_out_assign_proc : process(hash_out_V_data_V_1_payload_A, hash_out_V_data_V_1_payload_B, hash_out_V_data_V_1_sel)
    begin
        if ((hash_out_V_data_V_1_sel = ap_const_logic_1)) then 
            hash_out_V_data_V_1_data_out <= hash_out_V_data_V_1_payload_B;
        else 
            hash_out_V_data_V_1_data_out <= hash_out_V_data_V_1_payload_A;
        end if; 
    end process;

    hash_out_V_data_V_1_load_A <= (hash_out_V_data_V_1_state_cmp_full and not(hash_out_V_data_V_1_sel_wr));
    hash_out_V_data_V_1_load_B <= (hash_out_V_data_V_1_state_cmp_full and hash_out_V_data_V_1_sel_wr);
    hash_out_V_data_V_1_sel <= hash_out_V_data_V_1_sel_rd;
    hash_out_V_data_V_1_state_cmp_full <= '0' when (hash_out_V_data_V_1_state = ap_const_lv2_1) else '1';

    hash_out_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln83_reg_1002, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln83_reg_1002 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_out_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            hash_out_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    hash_out_V_data_V_1_vld_out <= hash_out_V_data_V_1_state(0);
    hash_out_V_keep_V_1_ack_out <= hash_out_TREADY;
    hash_out_V_keep_V_1_data_out <= ap_const_lv4_F;
    hash_out_V_keep_V_1_sel <= hash_out_V_keep_V_1_sel_rd;

    hash_out_V_keep_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln83_reg_1002, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln83_reg_1002 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_out_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            hash_out_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    hash_out_V_keep_V_1_vld_out <= hash_out_V_keep_V_1_state(0);
    hash_out_V_last_V_1_ack_in <= hash_out_V_last_V_1_state(1);
    hash_out_V_last_V_1_ack_out <= hash_out_TREADY;

    hash_out_V_last_V_1_data_out_assign_proc : process(hash_out_V_last_V_1_payload_A, hash_out_V_last_V_1_payload_B, hash_out_V_last_V_1_sel)
    begin
        if ((hash_out_V_last_V_1_sel = ap_const_logic_1)) then 
            hash_out_V_last_V_1_data_out <= hash_out_V_last_V_1_payload_B;
        else 
            hash_out_V_last_V_1_data_out <= hash_out_V_last_V_1_payload_A;
        end if; 
    end process;

    hash_out_V_last_V_1_load_A <= (hash_out_V_last_V_1_state_cmp_full and not(hash_out_V_last_V_1_sel_wr));
    hash_out_V_last_V_1_load_B <= (hash_out_V_last_V_1_state_cmp_full and hash_out_V_last_V_1_sel_wr);
    hash_out_V_last_V_1_sel <= hash_out_V_last_V_1_sel_rd;
    hash_out_V_last_V_1_state_cmp_full <= '0' when (hash_out_V_last_V_1_state = ap_const_lv2_1) else '1';

    hash_out_V_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln83_reg_1002, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln83_reg_1002 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_out_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            hash_out_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    hash_out_V_last_V_1_vld_out <= hash_out_V_last_V_1_state(0);
    hash_out_V_strb_V_1_ack_out <= hash_out_TREADY;
    hash_out_V_strb_V_1_data_out <= ap_const_lv4_F;
    hash_out_V_strb_V_1_sel <= hash_out_V_strb_V_1_sel_rd;

    hash_out_V_strb_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln83_reg_1002, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln83_reg_1002 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            hash_out_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            hash_out_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    hash_out_V_strb_V_1_vld_out <= hash_out_V_strb_V_1_state(0);
    i_3_fu_689_p2 <= std_logic_vector(unsigned(i1_0_reg_348) + unsigned(ap_const_lv4_1));
    i_fu_678_p2 <= std_logic_vector(unsigned(select_ln75_reg_949) + unsigned(ap_const_lv5_1));
    icmp_ln73_fu_469_p2 <= "1" when (indvar_flatten_reg_230 = tmp_reg_815) else "0";
    icmp_ln75_fu_512_p2 <= "1" when (i_0_reg_337 = ap_const_lv5_10) else "0";
    icmp_ln83_fu_683_p2 <= "1" when (i1_0_reg_348 = ap_const_lv4_8) else "0";
    out_word_data_V_fu_699_p9 <= i1_0_reg_348(3 - 1 downto 0);
    out_word_last_V_fu_713_p2 <= "1" when (i1_0_reg_348 = ap_const_lv4_7) else "0";
    select_ln73_1_fu_534_p3 <= 
        grp_sha256_transform_fu_359_ap_return_6 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_6_V_0_reg_253;
    select_ln73_2_fu_542_p3 <= 
        grp_sha256_transform_fu_359_ap_return_5 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_5_V_0_reg_265;
    select_ln73_3_fu_550_p3 <= 
        grp_sha256_transform_fu_359_ap_return_4 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_4_V_0_reg_277;
    select_ln73_4_fu_558_p3 <= 
        grp_sha256_transform_fu_359_ap_return_3 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_3_V_0_reg_289;
    select_ln73_5_fu_566_p3 <= 
        grp_sha256_transform_fu_359_ap_return_2 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_2_V_0_reg_301;
    select_ln73_6_fu_574_p3 <= 
        grp_sha256_transform_fu_359_ap_return_1 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_1_V_0_reg_313;
    select_ln73_7_fu_582_p3 <= 
        grp_sha256_transform_fu_359_ap_return_0 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_0_V_0_reg_325;
    select_ln73_fu_526_p3 <= 
        grp_sha256_transform_fu_359_ap_return_7 when (icmp_ln75_fu_512_p2(0) = '1') else 
        state_7_V_0_reg_241;
    select_ln75_fu_518_p3 <= 
        ap_const_lv5_0 when (icmp_ln75_fu_512_p2(0) = '1') else 
        i_0_reg_337;
    tmp_fu_397_p3 <= (num_blocks & ap_const_lv4_0);
    trunc_ln321_fu_594_p1 <= select_ln75_fu_518_p3(4 - 1 downto 0);
end behav;
