// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sha256_core,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=15.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.996000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=5937,HLS_SYN_LUT=2940,HLS_VERSION=2019_1}" *)

module sha256_core (
        ap_clk,
        ap_rst_n,
        data_in_TDATA,
        data_in_TVALID,
        data_in_TREADY,
        data_in_TKEEP,
        data_in_TSTRB,
        data_in_TLAST,
        hash_out_TDATA,
        hash_out_TVALID,
        hash_out_TREADY,
        hash_out_TKEEP,
        hash_out_TSTRB,
        hash_out_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp0_stage0 = 6'd16;
parameter    ap_ST_fsm_state8 = 6'd32;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] data_in_TDATA;
input   data_in_TVALID;
output   data_in_TREADY;
input  [3:0] data_in_TKEEP;
input  [3:0] data_in_TSTRB;
input  [0:0] data_in_TLAST;
output  [31:0] hash_out_TDATA;
output   hash_out_TVALID;
input   hash_out_TREADY;
output  [3:0] hash_out_TKEEP;
output  [3:0] hash_out_TSTRB;
output  [0:0] hash_out_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [31:0] data_in_V_data_V_0_data_out;
wire    data_in_V_data_V_0_vld_in;
wire    data_in_V_data_V_0_vld_out;
wire    data_in_V_data_V_0_ack_in;
reg    data_in_V_data_V_0_ack_out;
reg   [31:0] data_in_V_data_V_0_payload_A;
reg   [31:0] data_in_V_data_V_0_payload_B;
reg    data_in_V_data_V_0_sel_rd;
reg    data_in_V_data_V_0_sel_wr;
wire    data_in_V_data_V_0_sel;
wire    data_in_V_data_V_0_load_A;
wire    data_in_V_data_V_0_load_B;
reg   [1:0] data_in_V_data_V_0_state;
wire    data_in_V_data_V_0_state_cmp_full;
wire    data_in_V_last_V_0_vld_in;
reg    data_in_V_last_V_0_ack_out;
reg   [1:0] data_in_V_last_V_0_state;
reg   [31:0] hash_out_V_data_V_1_data_out;
reg    hash_out_V_data_V_1_vld_in;
wire    hash_out_V_data_V_1_vld_out;
wire    hash_out_V_data_V_1_ack_in;
wire    hash_out_V_data_V_1_ack_out;
reg   [31:0] hash_out_V_data_V_1_payload_A;
reg   [31:0] hash_out_V_data_V_1_payload_B;
reg    hash_out_V_data_V_1_sel_rd;
reg    hash_out_V_data_V_1_sel_wr;
wire    hash_out_V_data_V_1_sel;
wire    hash_out_V_data_V_1_load_A;
wire    hash_out_V_data_V_1_load_B;
reg   [1:0] hash_out_V_data_V_1_state;
wire    hash_out_V_data_V_1_state_cmp_full;
wire   [3:0] hash_out_V_keep_V_1_data_out;
reg    hash_out_V_keep_V_1_vld_in;
wire    hash_out_V_keep_V_1_vld_out;
wire    hash_out_V_keep_V_1_ack_out;
reg    hash_out_V_keep_V_1_sel_rd;
wire    hash_out_V_keep_V_1_sel;
reg   [1:0] hash_out_V_keep_V_1_state;
wire   [3:0] hash_out_V_strb_V_1_data_out;
reg    hash_out_V_strb_V_1_vld_in;
wire    hash_out_V_strb_V_1_vld_out;
wire    hash_out_V_strb_V_1_ack_out;
reg    hash_out_V_strb_V_1_sel_rd;
wire    hash_out_V_strb_V_1_sel;
reg   [1:0] hash_out_V_strb_V_1_state;
reg   [0:0] hash_out_V_last_V_1_data_out;
reg    hash_out_V_last_V_1_vld_in;
wire    hash_out_V_last_V_1_vld_out;
wire    hash_out_V_last_V_1_ack_in;
wire    hash_out_V_last_V_1_ack_out;
reg   [0:0] hash_out_V_last_V_1_payload_A;
reg   [0:0] hash_out_V_last_V_1_payload_B;
reg    hash_out_V_last_V_1_sel_rd;
reg    hash_out_V_last_V_1_sel_wr;
wire    hash_out_V_last_V_1_sel;
wire    hash_out_V_last_V_1_load_A;
wire    hash_out_V_last_V_1_load_B;
reg   [1:0] hash_out_V_last_V_1_state;
wire    hash_out_V_last_V_1_state_cmp_full;
wire   [31:0] num_blocks;
reg    data_in_TDATA_blk_n;
wire    ap_CS_fsm_state3;
reg   [0:0] icmp_ln73_reg_900;
reg    hash_out_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln83_reg_1002;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln83_reg_1002_pp0_iter1_reg;
reg   [3:0] i1_0_reg_348;
wire   [35:0] tmp_fu_397_p3;
reg   [35:0] tmp_reg_815;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln73_fu_469_p2;
wire   [35:0] add_ln73_fu_474_p2;
reg   [35:0] add_ln73_reg_904;
reg   [31:0] state_0_V_reg_909;
reg    ap_block_state3;
wire    grp_sha256_transform_fu_359_ap_ready;
wire    grp_sha256_transform_fu_359_ap_done;
reg   [31:0] state_1_V_reg_914;
reg   [31:0] state_2_V_reg_919;
reg   [31:0] state_3_V_reg_924;
reg   [31:0] state_4_V_reg_929;
reg   [31:0] state_5_V_reg_934;
reg   [31:0] state_6_V_reg_939;
reg   [31:0] state_7_V_reg_944;
wire   [4:0] select_ln75_fu_518_p3;
reg   [4:0] select_ln75_reg_949;
wire   [31:0] select_ln73_fu_526_p3;
reg   [31:0] select_ln73_reg_954;
wire   [31:0] select_ln73_1_fu_534_p3;
reg   [31:0] select_ln73_1_reg_959;
wire   [31:0] select_ln73_2_fu_542_p3;
reg   [31:0] select_ln73_2_reg_964;
wire   [31:0] select_ln73_3_fu_550_p3;
reg   [31:0] select_ln73_3_reg_969;
wire   [31:0] select_ln73_4_fu_558_p3;
reg   [31:0] select_ln73_4_reg_974;
wire   [31:0] select_ln73_5_fu_566_p3;
reg   [31:0] select_ln73_5_reg_979;
wire   [31:0] select_ln73_6_fu_574_p3;
reg   [31:0] select_ln73_6_reg_984;
wire   [31:0] select_ln73_7_fu_582_p3;
reg   [31:0] select_ln73_7_reg_989;
wire   [4:0] i_fu_678_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln83_fu_683_p2;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
reg    ap_block_state6_io;
wire    ap_block_state7_pp0_stage0_iter2;
reg    ap_block_state7_io;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] i_3_fu_689_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [31:0] out_word_data_V_fu_699_p10;
reg   [31:0] out_word_data_V_reg_1011;
wire   [0:0] out_word_last_V_fu_713_p2;
reg   [0:0] out_word_last_V_reg_1016;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
wire    grp_sha256_transform_fu_359_ap_start;
wire    grp_sha256_transform_fu_359_ap_idle;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_0;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_1;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_2;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_3;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_4;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_5;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_6;
wire   [31:0] grp_sha256_transform_fu_359_ap_return_7;
reg   [35:0] indvar_flatten_reg_230;
reg   [31:0] state_7_V_0_reg_241;
reg   [31:0] state_6_V_0_reg_253;
reg   [31:0] state_5_V_0_reg_265;
reg   [31:0] state_4_V_0_reg_277;
reg   [31:0] state_3_V_0_reg_289;
reg   [31:0] state_2_V_0_reg_301;
reg   [31:0] state_1_V_0_reg_313;
reg   [31:0] state_0_V_0_reg_325;
reg   [4:0] i_0_reg_337;
reg    grp_sha256_transform_fu_359_ap_start_reg;
reg   [31:0] tmp_data_V_fu_130;
wire   [3:0] trunc_ln321_fu_594_p1;
reg   [31:0] tmp_data_V_1_fu_134;
reg   [31:0] tmp_data_V_2_fu_138;
reg   [31:0] tmp_data_V_3_fu_142;
reg   [31:0] tmp_data_V_4_fu_146;
reg   [31:0] tmp_data_V_5_fu_150;
reg   [31:0] tmp_data_V_6_fu_154;
reg   [31:0] tmp_data_V_7_fu_158;
reg   [31:0] tmp_data_V_8_fu_162;
reg   [31:0] tmp_data_V_9_fu_166;
reg   [31:0] tmp_data_V_10_fu_170;
reg   [31:0] tmp_data_V_11_fu_174;
reg   [31:0] tmp_data_V_12_fu_178;
reg   [31:0] tmp_data_V_13_fu_182;
reg   [31:0] tmp_data_V_14_fu_186;
reg   [31:0] tmp_data_V_15_fu_190;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln75_fu_512_p2;
wire   [2:0] out_word_data_V_fu_699_p9;
wire    ap_CS_fsm_state8;
reg    ap_block_state8;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 data_in_V_data_V_0_sel_rd = 1'b0;
#0 data_in_V_data_V_0_sel_wr = 1'b0;
#0 data_in_V_data_V_0_state = 2'd0;
#0 data_in_V_last_V_0_state = 2'd0;
#0 hash_out_V_data_V_1_sel_rd = 1'b0;
#0 hash_out_V_data_V_1_sel_wr = 1'b0;
#0 hash_out_V_data_V_1_state = 2'd0;
#0 hash_out_V_keep_V_1_sel_rd = 1'b0;
#0 hash_out_V_keep_V_1_state = 2'd0;
#0 hash_out_V_strb_V_1_sel_rd = 1'b0;
#0 hash_out_V_strb_V_1_state = 2'd0;
#0 hash_out_V_last_V_1_sel_rd = 1'b0;
#0 hash_out_V_last_V_1_sel_wr = 1'b0;
#0 hash_out_V_last_V_1_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_sha256_transform_fu_359_ap_start_reg = 1'b0;
end

sha256_core_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
sha256_core_CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .num_blocks(num_blocks)
);

sha256_transform grp_sha256_transform_fu_359(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sha256_transform_fu_359_ap_start),
    .ap_done(grp_sha256_transform_fu_359_ap_done),
    .ap_idle(grp_sha256_transform_fu_359_ap_idle),
    .ap_ready(grp_sha256_transform_fu_359_ap_ready),
    .state_0_V_read(state_0_V_0_reg_325),
    .state_1_V_read(state_1_V_0_reg_313),
    .state_2_V_read(state_2_V_0_reg_301),
    .state_3_V_read(state_3_V_0_reg_289),
    .state_4_V_read(state_4_V_0_reg_277),
    .state_5_V_read(state_5_V_0_reg_265),
    .state_6_V_read(state_6_V_0_reg_253),
    .state_7_V_read(state_7_V_0_reg_241),
    .block_0_V_read(tmp_data_V_fu_130),
    .block_1_V_read(tmp_data_V_1_fu_134),
    .block_2_V_read(tmp_data_V_2_fu_138),
    .block_3_V_read(tmp_data_V_3_fu_142),
    .block_4_V_read(tmp_data_V_4_fu_146),
    .block_5_V_read(tmp_data_V_5_fu_150),
    .block_6_V_read(tmp_data_V_6_fu_154),
    .block_7_V_read(tmp_data_V_7_fu_158),
    .block_8_V_read(tmp_data_V_8_fu_162),
    .block_9_V_read(tmp_data_V_9_fu_166),
    .block_10_V_read(tmp_data_V_10_fu_170),
    .block_11_V_read(tmp_data_V_11_fu_174),
    .block_12_V_read(tmp_data_V_12_fu_178),
    .block_13_V_read(tmp_data_V_13_fu_182),
    .block_14_V_read(tmp_data_V_14_fu_186),
    .block_15_V_read(tmp_data_V_15_fu_190),
    .ap_return_0(grp_sha256_transform_fu_359_ap_return_0),
    .ap_return_1(grp_sha256_transform_fu_359_ap_return_1),
    .ap_return_2(grp_sha256_transform_fu_359_ap_return_2),
    .ap_return_3(grp_sha256_transform_fu_359_ap_return_3),
    .ap_return_4(grp_sha256_transform_fu_359_ap_return_4),
    .ap_return_5(grp_sha256_transform_fu_359_ap_return_5),
    .ap_return_6(grp_sha256_transform_fu_359_ap_return_6),
    .ap_return_7(grp_sha256_transform_fu_359_ap_return_7)
);

sha256_core_mux_8dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_8dEe_U37(
    .din0(state_0_V_reg_909),
    .din1(state_1_V_reg_914),
    .din2(state_2_V_reg_919),
    .din3(state_3_V_reg_924),
    .din4(state_4_V_reg_929),
    .din5(state_5_V_reg_934),
    .din6(state_6_V_reg_939),
    .din7(state_7_V_reg_944),
    .din8(out_word_data_V_fu_699_p9),
    .dout(out_word_data_V_fu_699_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state5)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((data_in_V_data_V_0_ack_out == 1'b1) & (data_in_V_data_V_0_vld_out == 1'b1))) begin
            data_in_V_data_V_0_sel_rd <= ~data_in_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((data_in_V_data_V_0_ack_in == 1'b1) & (data_in_V_data_V_0_vld_in == 1'b1))) begin
            data_in_V_data_V_0_sel_wr <= ~data_in_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((data_in_V_data_V_0_state == 2'd2) & (data_in_V_data_V_0_vld_in == 1'b0)) | ((data_in_V_data_V_0_state == 2'd3) & (data_in_V_data_V_0_vld_in == 1'b0) & (data_in_V_data_V_0_ack_out == 1'b1)))) begin
            data_in_V_data_V_0_state <= 2'd2;
        end else if ((((data_in_V_data_V_0_state == 2'd1) & (data_in_V_data_V_0_ack_out == 1'b0)) | ((data_in_V_data_V_0_state == 2'd3) & (data_in_V_data_V_0_ack_out == 1'b0) & (data_in_V_data_V_0_vld_in == 1'b1)))) begin
            data_in_V_data_V_0_state <= 2'd1;
        end else if (((~((data_in_V_data_V_0_vld_in == 1'b0) & (data_in_V_data_V_0_ack_out == 1'b1)) & ~((data_in_V_data_V_0_ack_out == 1'b0) & (data_in_V_data_V_0_vld_in == 1'b1)) & (data_in_V_data_V_0_state == 2'd3)) | ((data_in_V_data_V_0_state == 2'd1) & (data_in_V_data_V_0_ack_out == 1'b1)) | ((data_in_V_data_V_0_state == 2'd2) & (data_in_V_data_V_0_vld_in == 1'b1)))) begin
            data_in_V_data_V_0_state <= 2'd3;
        end else begin
            data_in_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        data_in_V_last_V_0_state <= 2'd0;
    end else begin
        if ((((data_in_V_last_V_0_state == 2'd2) & (data_in_V_last_V_0_vld_in == 1'b0)) | ((data_in_V_last_V_0_state == 2'd3) & (data_in_V_last_V_0_vld_in == 1'b0) & (data_in_V_last_V_0_ack_out == 1'b1)))) begin
            data_in_V_last_V_0_state <= 2'd2;
        end else if ((((data_in_V_last_V_0_state == 2'd1) & (data_in_V_last_V_0_ack_out == 1'b0)) | ((data_in_V_last_V_0_state == 2'd3) & (data_in_V_last_V_0_ack_out == 1'b0) & (data_in_V_last_V_0_vld_in == 1'b1)))) begin
            data_in_V_last_V_0_state <= 2'd1;
        end else if (((~((data_in_V_last_V_0_vld_in == 1'b0) & (data_in_V_last_V_0_ack_out == 1'b1)) & ~((data_in_V_last_V_0_ack_out == 1'b0) & (data_in_V_last_V_0_vld_in == 1'b1)) & (data_in_V_last_V_0_state == 2'd3)) | ((data_in_V_last_V_0_state == 2'd1) & (data_in_V_last_V_0_ack_out == 1'b1)) | ((data_in_V_last_V_0_state == 2'd2) & (data_in_V_last_V_0_vld_in == 1'b1)))) begin
            data_in_V_last_V_0_state <= 2'd3;
        end else begin
            data_in_V_last_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sha256_transform_fu_359_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sha256_transform_fu_359_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_transform_fu_359_ap_ready == 1'b1)) begin
            grp_sha256_transform_fu_359_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_data_V_1_sel_rd <= 1'b0;
    end else begin
        if (((hash_out_V_data_V_1_ack_out == 1'b1) & (hash_out_V_data_V_1_vld_out == 1'b1))) begin
            hash_out_V_data_V_1_sel_rd <= ~hash_out_V_data_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_data_V_1_sel_wr <= 1'b0;
    end else begin
        if (((hash_out_V_data_V_1_ack_in == 1'b1) & (hash_out_V_data_V_1_vld_in == 1'b1))) begin
            hash_out_V_data_V_1_sel_wr <= ~hash_out_V_data_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_data_V_1_state <= 2'd0;
    end else begin
        if ((((hash_out_V_data_V_1_state == 2'd2) & (hash_out_V_data_V_1_vld_in == 1'b0)) | ((hash_out_V_data_V_1_state == 2'd3) & (hash_out_V_data_V_1_vld_in == 1'b0) & (hash_out_V_data_V_1_ack_out == 1'b1)))) begin
            hash_out_V_data_V_1_state <= 2'd2;
        end else if ((((hash_out_V_data_V_1_state == 2'd1) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_data_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0) & (hash_out_V_data_V_1_vld_in == 1'b1)))) begin
            hash_out_V_data_V_1_state <= 2'd1;
        end else if (((~((hash_out_V_data_V_1_vld_in == 1'b0) & (hash_out_V_data_V_1_ack_out == 1'b1)) & ~((hash_out_TREADY == 1'b0) & (hash_out_V_data_V_1_vld_in == 1'b1)) & (hash_out_V_data_V_1_state == 2'd3)) | ((hash_out_V_data_V_1_state == 2'd1) & (hash_out_V_data_V_1_ack_out == 1'b1)) | ((hash_out_V_data_V_1_state == 2'd2) & (hash_out_V_data_V_1_vld_in == 1'b1)))) begin
            hash_out_V_data_V_1_state <= 2'd3;
        end else begin
            hash_out_V_data_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_keep_V_1_sel_rd <= 1'b0;
    end else begin
        if (((hash_out_V_keep_V_1_ack_out == 1'b1) & (hash_out_V_keep_V_1_vld_out == 1'b1))) begin
            hash_out_V_keep_V_1_sel_rd <= ~hash_out_V_keep_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_keep_V_1_state <= 2'd0;
    end else begin
        if ((((hash_out_V_keep_V_1_state == 2'd2) & (hash_out_V_keep_V_1_vld_in == 1'b0)) | ((hash_out_V_keep_V_1_state == 2'd3) & (hash_out_V_keep_V_1_vld_in == 1'b0) & (hash_out_V_keep_V_1_ack_out == 1'b1)))) begin
            hash_out_V_keep_V_1_state <= 2'd2;
        end else if ((((hash_out_V_keep_V_1_state == 2'd1) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_keep_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0) & (hash_out_V_keep_V_1_vld_in == 1'b1)))) begin
            hash_out_V_keep_V_1_state <= 2'd1;
        end else if (((~((hash_out_V_keep_V_1_vld_in == 1'b0) & (hash_out_V_keep_V_1_ack_out == 1'b1)) & ~((hash_out_TREADY == 1'b0) & (hash_out_V_keep_V_1_vld_in == 1'b1)) & (hash_out_V_keep_V_1_state == 2'd3)) | ((hash_out_V_keep_V_1_state == 2'd1) & (hash_out_V_keep_V_1_ack_out == 1'b1)) | ((hash_out_V_keep_V_1_state == 2'd2) & (hash_out_V_keep_V_1_vld_in == 1'b1)))) begin
            hash_out_V_keep_V_1_state <= 2'd3;
        end else begin
            hash_out_V_keep_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_last_V_1_sel_rd <= 1'b0;
    end else begin
        if (((hash_out_V_last_V_1_ack_out == 1'b1) & (hash_out_V_last_V_1_vld_out == 1'b1))) begin
            hash_out_V_last_V_1_sel_rd <= ~hash_out_V_last_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_last_V_1_sel_wr <= 1'b0;
    end else begin
        if (((hash_out_V_last_V_1_ack_in == 1'b1) & (hash_out_V_last_V_1_vld_in == 1'b1))) begin
            hash_out_V_last_V_1_sel_wr <= ~hash_out_V_last_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_last_V_1_state <= 2'd0;
    end else begin
        if ((((hash_out_V_last_V_1_state == 2'd2) & (hash_out_V_last_V_1_vld_in == 1'b0)) | ((hash_out_V_last_V_1_state == 2'd3) & (hash_out_V_last_V_1_vld_in == 1'b0) & (hash_out_V_last_V_1_ack_out == 1'b1)))) begin
            hash_out_V_last_V_1_state <= 2'd2;
        end else if ((((hash_out_V_last_V_1_state == 2'd1) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_last_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0) & (hash_out_V_last_V_1_vld_in == 1'b1)))) begin
            hash_out_V_last_V_1_state <= 2'd1;
        end else if (((~((hash_out_V_last_V_1_vld_in == 1'b0) & (hash_out_V_last_V_1_ack_out == 1'b1)) & ~((hash_out_TREADY == 1'b0) & (hash_out_V_last_V_1_vld_in == 1'b1)) & (hash_out_V_last_V_1_state == 2'd3)) | ((hash_out_V_last_V_1_state == 2'd1) & (hash_out_V_last_V_1_ack_out == 1'b1)) | ((hash_out_V_last_V_1_state == 2'd2) & (hash_out_V_last_V_1_vld_in == 1'b1)))) begin
            hash_out_V_last_V_1_state <= 2'd3;
        end else begin
            hash_out_V_last_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_strb_V_1_sel_rd <= 1'b0;
    end else begin
        if (((hash_out_V_strb_V_1_ack_out == 1'b1) & (hash_out_V_strb_V_1_vld_out == 1'b1))) begin
            hash_out_V_strb_V_1_sel_rd <= ~hash_out_V_strb_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        hash_out_V_strb_V_1_state <= 2'd0;
    end else begin
        if ((((hash_out_V_strb_V_1_state == 2'd2) & (hash_out_V_strb_V_1_vld_in == 1'b0)) | ((hash_out_V_strb_V_1_state == 2'd3) & (hash_out_V_strb_V_1_vld_in == 1'b0) & (hash_out_V_strb_V_1_ack_out == 1'b1)))) begin
            hash_out_V_strb_V_1_state <= 2'd2;
        end else if ((((hash_out_V_strb_V_1_state == 2'd1) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_strb_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0) & (hash_out_V_strb_V_1_vld_in == 1'b1)))) begin
            hash_out_V_strb_V_1_state <= 2'd1;
        end else if (((~((hash_out_V_strb_V_1_vld_in == 1'b0) & (hash_out_V_strb_V_1_ack_out == 1'b1)) & ~((hash_out_TREADY == 1'b0) & (hash_out_V_strb_V_1_vld_in == 1'b1)) & (hash_out_V_strb_V_1_state == 2'd3)) | ((hash_out_V_strb_V_1_state == 2'd1) & (hash_out_V_strb_V_1_ack_out == 1'b1)) | ((hash_out_V_strb_V_1_state == 2'd2) & (hash_out_V_strb_V_1_vld_in == 1'b1)))) begin
            hash_out_V_strb_V_1_state <= 2'd3;
        end else begin
            hash_out_V_strb_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i1_0_reg_348 <= 4'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln83_fu_683_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i1_0_reg_348 <= i_3_fu_689_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_0_reg_337 <= i_fu_678_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_337 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        indvar_flatten_reg_230 <= add_ln73_reg_904;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_230 <= 36'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_0_V_0_reg_325 <= select_ln73_7_reg_989;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_0_V_0_reg_325 <= 32'd1779033703;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_1_V_0_reg_313 <= select_ln73_6_reg_984;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_1_V_0_reg_313 <= 32'd3144134277;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_2_V_0_reg_301 <= select_ln73_5_reg_979;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_2_V_0_reg_301 <= 32'd1013904242;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_3_V_0_reg_289 <= select_ln73_4_reg_974;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_3_V_0_reg_289 <= 32'd2773480762;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_4_V_0_reg_277 <= select_ln73_3_reg_969;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_4_V_0_reg_277 <= 32'd1359893119;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_5_V_0_reg_265 <= select_ln73_2_reg_964;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_5_V_0_reg_265 <= 32'd2600822924;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_6_V_0_reg_253 <= select_ln73_1_reg_959;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_6_V_0_reg_253 <= 32'd528734635;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_7_V_0_reg_241 <= select_ln73_reg_954;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        state_7_V_0_reg_241 <= 32'd1541459225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln73_reg_904 <= add_ln73_fu_474_p2;
        icmp_ln73_reg_900 <= icmp_ln73_fu_469_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((data_in_V_data_V_0_load_A == 1'b1)) begin
        data_in_V_data_V_0_payload_A <= data_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((data_in_V_data_V_0_load_B == 1'b1)) begin
        data_in_V_data_V_0_payload_B <= data_in_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((hash_out_V_data_V_1_load_A == 1'b1)) begin
        hash_out_V_data_V_1_payload_A <= out_word_data_V_reg_1011;
    end
end

always @ (posedge ap_clk) begin
    if ((hash_out_V_data_V_1_load_B == 1'b1)) begin
        hash_out_V_data_V_1_payload_B <= out_word_data_V_reg_1011;
    end
end

always @ (posedge ap_clk) begin
    if ((hash_out_V_last_V_1_load_A == 1'b1)) begin
        hash_out_V_last_V_1_payload_A <= out_word_last_V_reg_1016;
    end
end

always @ (posedge ap_clk) begin
    if ((hash_out_V_last_V_1_load_B == 1'b1)) begin
        hash_out_V_last_V_1_payload_B <= out_word_last_V_reg_1016;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln83_reg_1002 <= icmp_ln83_fu_683_p2;
        icmp_ln83_reg_1002_pp0_iter1_reg <= icmp_ln83_reg_1002;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln83_fu_683_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_word_data_V_reg_1011 <= out_word_data_V_fu_699_p10;
        out_word_last_V_reg_1016 <= out_word_last_V_fu_713_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        select_ln73_1_reg_959 <= select_ln73_1_fu_534_p3;
        select_ln73_2_reg_964 <= select_ln73_2_fu_542_p3;
        select_ln73_3_reg_969 <= select_ln73_3_fu_550_p3;
        select_ln73_4_reg_974 <= select_ln73_4_fu_558_p3;
        select_ln73_5_reg_979 <= select_ln73_5_fu_566_p3;
        select_ln73_6_reg_984 <= select_ln73_6_fu_574_p3;
        select_ln73_7_reg_989 <= select_ln73_7_fu_582_p3;
        select_ln73_reg_954 <= select_ln73_fu_526_p3;
        select_ln75_reg_949 <= select_ln75_fu_518_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (1'b1 == ap_CS_fsm_state3))) begin
        state_0_V_reg_909 <= grp_sha256_transform_fu_359_ap_return_0;
        state_1_V_reg_914 <= grp_sha256_transform_fu_359_ap_return_1;
        state_2_V_reg_919 <= grp_sha256_transform_fu_359_ap_return_2;
        state_3_V_reg_924 <= grp_sha256_transform_fu_359_ap_return_3;
        state_4_V_reg_929 <= grp_sha256_transform_fu_359_ap_return_4;
        state_5_V_reg_934 <= grp_sha256_transform_fu_359_ap_return_5;
        state_6_V_reg_939 <= grp_sha256_transform_fu_359_ap_return_6;
        state_7_V_reg_944 <= grp_sha256_transform_fu_359_ap_return_7;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd10) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_10_fu_170 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd11) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_11_fu_174 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd12) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_12_fu_178 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd13) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_13_fu_182 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd14) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_14_fu_186 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd15) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_15_fu_190 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd1) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_1_fu_134 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd2) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_2_fu_138 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd3) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_3_fu_142 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd4) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_4_fu_146 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd5) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_5_fu_150 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd6) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_6_fu_154 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd7) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_7_fu_158 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd8) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_8_fu_162 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd9) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_9_fu_166 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (trunc_ln321_fu_594_p1 == 4'd0) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_data_V_fu_130 <= data_in_V_data_V_0_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_reg_815[35 : 4] <= tmp_fu_397_p3[35 : 4];
    end
end

always @ (*) begin
    if ((icmp_ln83_fu_683_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((~((hash_out_V_last_V_1_state == 2'd1) | (hash_out_V_strb_V_1_state == 2'd1) | (hash_out_V_keep_V_1_state == 2'd1) | (hash_out_V_data_V_1_state == 2'd1) | ((hash_out_V_last_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_strb_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_keep_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_data_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((hash_out_V_last_V_1_state == 2'd1) | (hash_out_V_strb_V_1_state == 2'd1) | (hash_out_V_keep_V_1_state == 2'd1) | (hash_out_V_data_V_1_state == 2'd1) | ((hash_out_V_last_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_strb_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_keep_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_data_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state8))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_in_TDATA_blk_n = data_in_V_data_V_0_state[1'd0];
    end else begin
        data_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_in_V_data_V_0_ack_out = 1'b1;
    end else begin
        data_in_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((data_in_V_data_V_0_sel == 1'b1)) begin
        data_in_V_data_V_0_data_out = data_in_V_data_V_0_payload_B;
    end else begin
        data_in_V_data_V_0_data_out = data_in_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_in_V_last_V_0_ack_out = 1'b1;
    end else begin
        data_in_V_last_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln83_reg_1002_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln83_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        hash_out_TDATA_blk_n = hash_out_V_data_V_1_state[1'd1];
    end else begin
        hash_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((hash_out_V_data_V_1_sel == 1'b1)) begin
        hash_out_V_data_V_1_data_out = hash_out_V_data_V_1_payload_B;
    end else begin
        hash_out_V_data_V_1_data_out = hash_out_V_data_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln83_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hash_out_V_data_V_1_vld_in = 1'b1;
    end else begin
        hash_out_V_data_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln83_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hash_out_V_keep_V_1_vld_in = 1'b1;
    end else begin
        hash_out_V_keep_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((hash_out_V_last_V_1_sel == 1'b1)) begin
        hash_out_V_last_V_1_data_out = hash_out_V_last_V_1_payload_B;
    end else begin
        hash_out_V_last_V_1_data_out = hash_out_V_last_V_1_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln83_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hash_out_V_last_V_1_vld_in = 1'b1;
    end else begin
        hash_out_V_last_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln83_reg_1002 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hash_out_V_strb_V_1_vld_in = 1'b1;
    end else begin
        hash_out_V_strb_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((grp_sha256_transform_fu_359_ap_done == 1'b0) | ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0))) & (icmp_ln73_reg_900 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln83_fu_683_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln83_fu_683_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            if ((~((hash_out_V_last_V_1_state == 2'd1) | (hash_out_V_strb_V_1_state == 2'd1) | (hash_out_V_keep_V_1_state == 2'd1) | (hash_out_V_data_V_1_state == 2'd1) | ((hash_out_V_last_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_strb_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_keep_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_data_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0))) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln73_fu_474_p2 = (indvar_flatten_reg_230 + 36'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state7_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state7_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state6_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln73_reg_900 == 1'd0) & (data_in_V_data_V_0_vld_out == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((icmp_ln83_reg_1002 == 1'd0) & (hash_out_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((icmp_ln83_reg_1002_pp0_iter1_reg == 1'd0) & (hash_out_V_data_V_1_ack_in == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8 = ((hash_out_V_last_V_1_state == 2'd1) | (hash_out_V_strb_V_1_state == 2'd1) | (hash_out_V_keep_V_1_state == 2'd1) | (hash_out_V_data_V_1_state == 2'd1) | ((hash_out_V_last_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_strb_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_keep_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)) | ((hash_out_V_data_V_1_state == 2'd3) & (hash_out_TREADY == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign data_in_TREADY = data_in_V_last_V_0_state[1'd1];

assign data_in_V_data_V_0_ack_in = data_in_V_data_V_0_state[1'd1];

assign data_in_V_data_V_0_load_A = (~data_in_V_data_V_0_sel_wr & data_in_V_data_V_0_state_cmp_full);

assign data_in_V_data_V_0_load_B = (data_in_V_data_V_0_state_cmp_full & data_in_V_data_V_0_sel_wr);

assign data_in_V_data_V_0_sel = data_in_V_data_V_0_sel_rd;

assign data_in_V_data_V_0_state_cmp_full = ((data_in_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign data_in_V_data_V_0_vld_in = data_in_TVALID;

assign data_in_V_data_V_0_vld_out = data_in_V_data_V_0_state[1'd0];

assign data_in_V_last_V_0_vld_in = data_in_TVALID;

assign grp_sha256_transform_fu_359_ap_start = grp_sha256_transform_fu_359_ap_start_reg;

assign hash_out_TDATA = hash_out_V_data_V_1_data_out;

assign hash_out_TKEEP = hash_out_V_keep_V_1_data_out;

assign hash_out_TLAST = hash_out_V_last_V_1_data_out;

assign hash_out_TSTRB = hash_out_V_strb_V_1_data_out;

assign hash_out_TVALID = hash_out_V_last_V_1_state[1'd0];

assign hash_out_V_data_V_1_ack_in = hash_out_V_data_V_1_state[1'd1];

assign hash_out_V_data_V_1_ack_out = hash_out_TREADY;

assign hash_out_V_data_V_1_load_A = (hash_out_V_data_V_1_state_cmp_full & ~hash_out_V_data_V_1_sel_wr);

assign hash_out_V_data_V_1_load_B = (hash_out_V_data_V_1_state_cmp_full & hash_out_V_data_V_1_sel_wr);

assign hash_out_V_data_V_1_sel = hash_out_V_data_V_1_sel_rd;

assign hash_out_V_data_V_1_state_cmp_full = ((hash_out_V_data_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign hash_out_V_data_V_1_vld_out = hash_out_V_data_V_1_state[1'd0];

assign hash_out_V_keep_V_1_ack_out = hash_out_TREADY;

assign hash_out_V_keep_V_1_data_out = 4'd15;

assign hash_out_V_keep_V_1_sel = hash_out_V_keep_V_1_sel_rd;

assign hash_out_V_keep_V_1_vld_out = hash_out_V_keep_V_1_state[1'd0];

assign hash_out_V_last_V_1_ack_in = hash_out_V_last_V_1_state[1'd1];

assign hash_out_V_last_V_1_ack_out = hash_out_TREADY;

assign hash_out_V_last_V_1_load_A = (hash_out_V_last_V_1_state_cmp_full & ~hash_out_V_last_V_1_sel_wr);

assign hash_out_V_last_V_1_load_B = (hash_out_V_last_V_1_state_cmp_full & hash_out_V_last_V_1_sel_wr);

assign hash_out_V_last_V_1_sel = hash_out_V_last_V_1_sel_rd;

assign hash_out_V_last_V_1_state_cmp_full = ((hash_out_V_last_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign hash_out_V_last_V_1_vld_out = hash_out_V_last_V_1_state[1'd0];

assign hash_out_V_strb_V_1_ack_out = hash_out_TREADY;

assign hash_out_V_strb_V_1_data_out = 4'd15;

assign hash_out_V_strb_V_1_sel = hash_out_V_strb_V_1_sel_rd;

assign hash_out_V_strb_V_1_vld_out = hash_out_V_strb_V_1_state[1'd0];

assign i_3_fu_689_p2 = (i1_0_reg_348 + 4'd1);

assign i_fu_678_p2 = (select_ln75_reg_949 + 5'd1);

assign icmp_ln73_fu_469_p2 = ((indvar_flatten_reg_230 == tmp_reg_815) ? 1'b1 : 1'b0);

assign icmp_ln75_fu_512_p2 = ((i_0_reg_337 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_683_p2 = ((i1_0_reg_348 == 4'd8) ? 1'b1 : 1'b0);

assign out_word_data_V_fu_699_p9 = i1_0_reg_348[2:0];

assign out_word_last_V_fu_713_p2 = ((i1_0_reg_348 == 4'd7) ? 1'b1 : 1'b0);

assign select_ln73_1_fu_534_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_6 : state_6_V_0_reg_253);

assign select_ln73_2_fu_542_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_5 : state_5_V_0_reg_265);

assign select_ln73_3_fu_550_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_4 : state_4_V_0_reg_277);

assign select_ln73_4_fu_558_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_3 : state_3_V_0_reg_289);

assign select_ln73_5_fu_566_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_2 : state_2_V_0_reg_301);

assign select_ln73_6_fu_574_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_1 : state_1_V_0_reg_313);

assign select_ln73_7_fu_582_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_0 : state_0_V_0_reg_325);

assign select_ln73_fu_526_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? grp_sha256_transform_fu_359_ap_return_7 : state_7_V_0_reg_241);

assign select_ln75_fu_518_p3 = ((icmp_ln75_fu_512_p2[0:0] === 1'b1) ? 5'd0 : i_0_reg_337);

assign tmp_fu_397_p3 = {{num_blocks}, {4'd0}};

assign trunc_ln321_fu_594_p1 = select_ln75_fu_518_p3[3:0];

always @ (posedge ap_clk) begin
    tmp_reg_815[3:0] <= 4'b0000;
end

endmodule //sha256_core
