// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_transform (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        state_0_V_read,
        state_1_V_read,
        state_2_V_read,
        state_3_V_read,
        state_4_V_read,
        state_5_V_read,
        state_6_V_read,
        state_7_V_read,
        block_0_V_read,
        block_1_V_read,
        block_2_V_read,
        block_3_V_read,
        block_4_V_read,
        block_5_V_read,
        block_6_V_read,
        block_7_V_read,
        block_8_V_read,
        block_9_V_read,
        block_10_V_read,
        block_11_V_read,
        block_12_V_read,
        block_13_V_read,
        block_14_V_read,
        block_15_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] state_0_V_read;
input  [31:0] state_1_V_read;
input  [31:0] state_2_V_read;
input  [31:0] state_3_V_read;
input  [31:0] state_4_V_read;
input  [31:0] state_5_V_read;
input  [31:0] state_6_V_read;
input  [31:0] state_7_V_read;
input  [31:0] block_0_V_read;
input  [31:0] block_1_V_read;
input  [31:0] block_2_V_read;
input  [31:0] block_3_V_read;
input  [31:0] block_4_V_read;
input  [31:0] block_5_V_read;
input  [31:0] block_6_V_read;
input  [31:0] block_7_V_read;
input  [31:0] block_8_V_read;
input  [31:0] block_9_V_read;
input  [31:0] block_10_V_read;
input  [31:0] block_11_V_read;
input  [31:0] block_12_V_read;
input  [31:0] block_13_V_read;
input  [31:0] block_14_V_read;
input  [31:0] block_15_V_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;
reg[31:0] ap_return_4;
reg[31:0] ap_return_5;
reg[31:0] ap_return_6;
reg[31:0] ap_return_7;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [5:0] K_address0;
reg    K_ce0;
wire   [31:0] K_q0;
reg   [31:0] W_15_V_load_reg_2908;
wire    ap_CS_fsm_state2;
reg   [31:0] W_15_V_1_load_reg_2917;
reg   [31:0] W_15_V_2_load_reg_2926;
reg   [31:0] W_15_V_3_load_reg_2935;
reg   [31:0] W_15_V_4_load_reg_2944;
reg   [31:0] W_15_V_5_load_reg_2953;
reg   [31:0] W_15_V_6_load_reg_2962;
reg   [31:0] W_15_V_7_load_reg_2971;
reg   [31:0] W_15_V_8_load_reg_2980;
reg   [31:0] W_15_V_9_load_reg_2990;
reg   [31:0] W_15_V_10_load_reg_3000;
reg   [31:0] W_15_V_11_load_reg_3010;
reg   [31:0] W_15_V_12_load_reg_3020;
reg   [31:0] W_15_V_13_load_reg_3030;
reg   [31:0] W_15_V_14_load_reg_3043;
wire   [4:0] i_fu_1020_p2;
reg   [4:0] i_reg_3059;
reg   [31:0] W_63_V_load_reg_3352;
wire    ap_CS_fsm_state4;
reg   [31:0] W_63_V_1_load_reg_3365;
reg   [31:0] W_63_V_2_load_reg_3378;
reg   [31:0] W_63_V_3_load_reg_3391;
reg   [31:0] W_63_V_4_load_reg_3404;
reg   [31:0] W_63_V_5_load_reg_3417;
reg   [31:0] W_63_V_6_load_reg_3430;
reg   [31:0] W_63_V_7_load_reg_3443;
reg   [31:0] W_63_V_8_load_reg_3456;
reg   [31:0] W_63_V_9_load_reg_3469;
reg   [31:0] W_63_V_10_load_reg_3482;
reg   [31:0] W_63_V_11_load_reg_3495;
reg   [31:0] W_63_V_12_load_reg_3508;
reg   [31:0] W_63_V_13_load_reg_3521;
reg   [31:0] W_63_V_14_load_reg_3534;
reg   [31:0] W_63_V_15_load_reg_3547;
reg   [31:0] W_63_V_16_load_reg_3560;
reg   [31:0] W_63_V_17_load_reg_3573;
reg   [31:0] W_63_V_18_load_reg_3586;
reg   [31:0] W_63_V_19_load_reg_3599;
reg   [31:0] W_63_V_20_load_reg_3612;
reg   [31:0] W_63_V_21_load_reg_3625;
reg   [31:0] W_63_V_22_load_reg_3638;
reg   [31:0] W_63_V_23_load_reg_3651;
reg   [31:0] W_63_V_24_load_reg_3664;
reg   [31:0] W_63_V_25_load_reg_3677;
reg   [31:0] W_63_V_26_load_reg_3690;
reg   [31:0] W_63_V_27_load_reg_3703;
reg   [31:0] W_63_V_28_load_reg_3716;
reg   [31:0] W_63_V_29_load_reg_3729;
reg   [31:0] W_63_V_30_load_reg_3742;
reg   [31:0] W_63_V_31_load_reg_3755;
reg   [31:0] W_63_V_32_load_reg_3784;
wire   [5:0] trunc_ln20_fu_1237_p1;
reg   [5:0] trunc_ln20_reg_3831;
wire   [0:0] icmp_ln18_fu_1231_p2;
wire   [6:0] i_2_fu_2234_p2;
wire    ap_CS_fsm_state6;
wire   [6:0] i_1_fu_2246_p2;
reg   [6:0] i_1_reg_3850;
wire    ap_CS_fsm_state7;
wire   [31:0] ret_V_28_fu_2354_p2;
reg   [31:0] ret_V_28_reg_3855;
wire   [0:0] icmp_ln36_fu_2240_p2;
wire   [31:0] add_ln209_2_fu_2461_p2;
reg   [31:0] add_ln209_2_reg_3865;
wire   [31:0] ret_V_35_fu_2485_p2;
reg   [31:0] ret_V_35_reg_3870;
wire   [31:0] e_V_fu_2667_p2;
wire    ap_CS_fsm_state8;
wire   [31:0] a_V_fu_2679_p2;
wire   [4:0] ap_phi_mux_i_0_phi_fu_711_p4;
reg   [4:0] i_0_reg_707;
wire    ap_CS_fsm_state3;
reg   [6:0] i1_0_reg_718;
wire   [0:0] icmp_ln14_fu_1014_p2;
reg   [31:0] phi_ln20_reg_730;
reg   [31:0] lhs_V_9_reg_831;
reg   [31:0] rhs_V_14_reg_841;
reg   [31:0] rhs_V_15_reg_852;
reg   [31:0] p_0535_0_reg_863;
reg   [31:0] lhs_V_reg_874;
reg   [31:0] rhs_V_reg_884;
reg   [31:0] rhs_V_13_reg_895;
reg   [31:0] p_0478_0_reg_906;
reg   [6:0] i2_0_reg_916;
wire   [63:0] zext_ln40_fu_2360_p1;
reg   [31:0] W_15_V_fu_294;
wire   [31:0] W_0_V_fu_1030_p18;
reg   [31:0] W_15_V_1_fu_298;
reg   [31:0] W_15_V_2_fu_302;
reg   [31:0] W_15_V_3_fu_306;
reg   [31:0] W_15_V_4_fu_310;
reg   [31:0] W_15_V_5_fu_314;
reg   [31:0] W_15_V_6_fu_318;
reg   [31:0] W_15_V_7_fu_322;
reg   [31:0] W_15_V_8_fu_326;
reg   [31:0] W_15_V_9_fu_330;
reg   [31:0] W_15_V_10_fu_334;
reg   [31:0] W_15_V_11_fu_338;
reg   [31:0] W_15_V_12_fu_342;
reg   [31:0] W_15_V_13_fu_346;
reg   [31:0] W_15_V_14_fu_350;
reg   [31:0] W_15_V_15_fu_354;
wire    ap_CS_fsm_state5;
reg   [31:0] W_63_V_fu_358;
wire   [31:0] W_16_V_fu_1988_p2;
reg   [31:0] W_63_V_1_fu_362;
reg   [31:0] W_63_V_2_fu_366;
reg   [31:0] W_63_V_3_fu_370;
reg   [31:0] W_63_V_4_fu_374;
reg   [31:0] W_63_V_5_fu_378;
reg   [31:0] W_63_V_6_fu_382;
reg   [31:0] W_63_V_7_fu_386;
reg   [31:0] W_63_V_8_fu_390;
reg   [31:0] W_63_V_9_fu_394;
reg   [31:0] W_63_V_10_fu_398;
reg   [31:0] W_63_V_11_fu_402;
reg   [31:0] W_63_V_12_fu_406;
reg   [31:0] W_63_V_13_fu_410;
reg   [31:0] W_63_V_14_fu_414;
reg   [31:0] W_63_V_15_fu_418;
reg   [31:0] W_63_V_16_fu_422;
reg   [31:0] W_63_V_17_fu_426;
reg   [31:0] W_63_V_18_fu_430;
reg   [31:0] W_63_V_19_fu_434;
reg   [31:0] W_63_V_20_fu_438;
reg   [31:0] W_63_V_21_fu_442;
reg   [31:0] W_63_V_22_fu_446;
reg   [31:0] W_63_V_23_fu_450;
reg   [31:0] W_63_V_24_fu_454;
reg   [31:0] W_63_V_25_fu_458;
reg   [31:0] W_63_V_26_fu_462;
reg   [31:0] W_63_V_27_fu_466;
reg   [31:0] W_63_V_28_fu_470;
reg   [31:0] W_63_V_29_fu_474;
reg   [31:0] W_63_V_30_fu_478;
reg   [31:0] W_63_V_31_fu_482;
reg   [31:0] W_63_V_32_fu_486;
reg   [31:0] W_63_V_33_fu_490;
reg   [31:0] W_63_V_34_fu_494;
reg   [31:0] W_63_V_35_fu_498;
reg   [31:0] W_63_V_36_fu_502;
reg   [31:0] W_63_V_37_fu_506;
reg   [31:0] W_63_V_38_fu_510;
reg   [31:0] W_63_V_39_fu_514;
reg   [31:0] W_63_V_40_fu_518;
reg   [31:0] W_63_V_41_fu_522;
reg   [31:0] W_63_V_42_fu_526;
reg   [31:0] W_63_V_43_fu_530;
reg   [31:0] W_63_V_44_fu_534;
reg   [31:0] W_63_V_45_fu_538;
reg   [31:0] W_63_V_46_fu_542;
reg   [31:0] W_63_V_47_fu_546;
wire   [3:0] W_0_V_fu_1030_p17;
wire   [6:0] trunc_ln1503_6_fu_1251_p1;
wire   [24:0] r_V_fu_1241_p4;
wire   [31:0] phi_ln20_1_fu_1263_p66;
wire   [17:0] trunc_ln1503_7_fu_1342_p1;
wire   [13:0] r_V_6_fu_1332_p4;
wire   [31:0] phi_ln_fu_1354_p66;
wire   [28:0] r_V_7_fu_1423_p4;
wire   [31:0] ret_V_fu_1255_p3;
wire   [31:0] r_V_14_fu_1433_p1;
wire   [31:0] xor_ln1357_7_fu_1437_p2;
wire   [31:0] ret_V_17_fu_1346_p3;
wire   [31:0] phi_ln1_fu_1449_p66;
wire   [16:0] trunc_ln1503_8_fu_1557_p1;
wire   [14:0] r_V_8_fu_1547_p4;
wire   [31:0] phi_ln21_1_fu_1569_p66;
wire   [18:0] trunc_ln1503_9_fu_1677_p1;
wire   [12:0] r_V_9_fu_1667_p4;
wire   [31:0] phi_ln1503_1_fu_1689_p66;
wire   [21:0] r_V_10_fu_1787_p4;
wire   [31:0] ret_V_19_fu_1561_p3;
wire   [31:0] r_V_15_fu_1797_p1;
wire   [31:0] xor_ln1357_9_fu_1801_p2;
wire   [31:0] ret_V_20_fu_1681_p3;
wire   [31:0] ret_V_21_fu_1807_p2;
wire   [31:0] phi_ln2_fu_1813_p66;
wire   [31:0] phi_ln215_1_fu_1883_p66;
wire   [31:0] ret_V_18_fu_1443_p2;
wire   [31:0] add_ln209_7_fu_1976_p2;
wire   [31:0] add_ln209_8_fu_1982_p2;
wire   [5:0] trunc_ln1503_fu_2268_p1;
wire   [25:0] r_V_s_fu_2258_p4;
wire   [10:0] trunc_ln1503_1_fu_2290_p1;
wire   [20:0] r_V_1_fu_2280_p4;
wire   [24:0] trunc_ln1503_2_fu_2312_p1;
wire   [6:0] r_V_2_fu_2302_p4;
wire   [31:0] ret_V_22_fu_2272_p3;
wire   [31:0] ret_V_24_fu_2316_p3;
wire   [31:0] xor_ln1357_fu_2324_p2;
wire   [31:0] ret_V_23_fu_2294_p3;
wire   [31:0] r_V_16_fu_2342_p2;
wire   [31:0] ret_V_27_fu_2348_p2;
wire   [31:0] ret_V_26_fu_2336_p2;
wire   [5:0] tmp_1_fu_2369_p65;
wire   [31:0] tmp_1_fu_2369_p66;
wire   [31:0] add_ln209_1_fu_2455_p2;
wire   [31:0] ret_V_25_fu_2330_p2;
wire   [31:0] xor_ln1357_5_fu_2467_p2;
wire   [31:0] ret_V_33_fu_2473_p2;
wire   [31:0] ret_V_34_fu_2479_p2;
wire   [31:0] add_ln700_fu_2491_p2;
wire   [31:0] add_ln700_1_fu_2496_p2;
wire   [31:0] add_ln700_2_fu_2501_p2;
wire   [31:0] add_ln700_3_fu_2506_p2;
wire   [31:0] add_ln700_4_fu_2511_p2;
wire   [31:0] add_ln700_5_fu_2516_p2;
wire   [31:0] add_ln700_6_fu_2521_p2;
wire   [31:0] add_ln700_7_fu_2526_p2;
wire   [31:0] add_ln209_fu_2579_p2;
wire   [1:0] trunc_ln1503_3_fu_2599_p1;
wire   [29:0] r_V_3_fu_2589_p4;
wire   [12:0] trunc_ln1503_4_fu_2621_p1;
wire   [18:0] r_V_4_fu_2611_p4;
wire   [21:0] trunc_ln1503_5_fu_2643_p1;
wire   [9:0] r_V_5_fu_2633_p4;
wire   [31:0] ret_V_29_fu_2603_p3;
wire   [31:0] ret_V_31_fu_2647_p3;
wire   [31:0] xor_ln1357_3_fu_2655_p2;
wire   [31:0] ret_V_30_fu_2625_p3;
wire   [31:0] t1_V_fu_2584_p2;
wire   [31:0] ret_V_32_fu_2661_p2;
wire   [31:0] add_ln209_5_fu_2673_p2;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [31:0] ap_return_4_preg;
reg   [31:0] ap_return_5_preg;
reg   [31:0] ap_return_6_preg;
reg   [31:0] ap_return_7_preg;
reg   [7:0] ap_NS_fsm;
reg    ap_condition_533;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
#0 ap_return_4_preg = 32'd0;
#0 ap_return_5_preg = 32'd0;
#0 ap_return_6_preg = 32'd0;
#0 ap_return_7_preg = 32'd0;
end

sha256_transform_K #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
K_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_address0),
    .ce0(K_ce0),
    .q0(K_q0)
);

sha256_core_mux_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_1bkb_U1(
    .din0(block_0_V_read),
    .din1(block_1_V_read),
    .din2(block_2_V_read),
    .din3(block_3_V_read),
    .din4(block_4_V_read),
    .din5(block_5_V_read),
    .din6(block_6_V_read),
    .din7(block_7_V_read),
    .din8(block_8_V_read),
    .din9(block_9_V_read),
    .din10(block_10_V_read),
    .din11(block_11_V_read),
    .din12(block_12_V_read),
    .din13(block_13_V_read),
    .din14(block_14_V_read),
    .din15(block_15_V_read),
    .din16(W_0_V_fu_1030_p17),
    .dout(W_0_V_fu_1030_p18)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U2(
    .din0(W_63_V_32_load_reg_3784),
    .din1(W_63_V_32_load_reg_3784),
    .din2(W_63_V_32_load_reg_3784),
    .din3(W_63_V_32_load_reg_3784),
    .din4(W_63_V_32_load_reg_3784),
    .din5(W_63_V_32_load_reg_3784),
    .din6(W_63_V_32_load_reg_3784),
    .din7(W_63_V_32_load_reg_3784),
    .din8(W_63_V_32_load_reg_3784),
    .din9(W_63_V_32_load_reg_3784),
    .din10(W_63_V_32_load_reg_3784),
    .din11(W_63_V_32_load_reg_3784),
    .din12(W_63_V_32_load_reg_3784),
    .din13(W_63_V_32_load_reg_3784),
    .din14(W_63_V_32_load_reg_3784),
    .din15(W_63_V_32_load_reg_3784),
    .din16(W_15_V_load_reg_2908),
    .din17(W_15_V_1_load_reg_2917),
    .din18(W_15_V_2_load_reg_2926),
    .din19(W_15_V_3_load_reg_2935),
    .din20(W_15_V_4_load_reg_2944),
    .din21(W_15_V_5_load_reg_2953),
    .din22(W_15_V_6_load_reg_2962),
    .din23(W_15_V_7_load_reg_2971),
    .din24(W_15_V_8_load_reg_2980),
    .din25(W_15_V_9_load_reg_2990),
    .din26(W_15_V_10_load_reg_3000),
    .din27(W_15_V_11_load_reg_3010),
    .din28(W_15_V_12_load_reg_3020),
    .din29(W_15_V_13_load_reg_3030),
    .din30(W_15_V_14_load_reg_3043),
    .din31(W_63_V_load_reg_3352),
    .din32(W_63_V_1_load_reg_3365),
    .din33(W_63_V_2_load_reg_3378),
    .din34(W_63_V_3_load_reg_3391),
    .din35(W_63_V_4_load_reg_3404),
    .din36(W_63_V_5_load_reg_3417),
    .din37(W_63_V_6_load_reg_3430),
    .din38(W_63_V_7_load_reg_3443),
    .din39(W_63_V_8_load_reg_3456),
    .din40(W_63_V_9_load_reg_3469),
    .din41(W_63_V_10_load_reg_3482),
    .din42(W_63_V_11_load_reg_3495),
    .din43(W_63_V_12_load_reg_3508),
    .din44(W_63_V_13_load_reg_3521),
    .din45(W_63_V_14_load_reg_3534),
    .din46(W_63_V_15_load_reg_3547),
    .din47(W_63_V_16_load_reg_3560),
    .din48(W_63_V_17_load_reg_3573),
    .din49(W_63_V_18_load_reg_3586),
    .din50(W_63_V_19_load_reg_3599),
    .din51(W_63_V_20_load_reg_3612),
    .din52(W_63_V_21_load_reg_3625),
    .din53(W_63_V_22_load_reg_3638),
    .din54(W_63_V_23_load_reg_3651),
    .din55(W_63_V_24_load_reg_3664),
    .din56(W_63_V_25_load_reg_3677),
    .din57(W_63_V_26_load_reg_3690),
    .din58(W_63_V_27_load_reg_3703),
    .din59(W_63_V_28_load_reg_3716),
    .din60(W_63_V_29_load_reg_3729),
    .din61(W_63_V_30_load_reg_3742),
    .din62(W_63_V_31_load_reg_3755),
    .din63(W_63_V_32_load_reg_3784),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln20_1_fu_1263_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U3(
    .din0(W_63_V_32_load_reg_3784),
    .din1(W_63_V_32_load_reg_3784),
    .din2(W_63_V_32_load_reg_3784),
    .din3(W_63_V_32_load_reg_3784),
    .din4(W_63_V_32_load_reg_3784),
    .din5(W_63_V_32_load_reg_3784),
    .din6(W_63_V_32_load_reg_3784),
    .din7(W_63_V_32_load_reg_3784),
    .din8(W_63_V_32_load_reg_3784),
    .din9(W_63_V_32_load_reg_3784),
    .din10(W_63_V_32_load_reg_3784),
    .din11(W_63_V_32_load_reg_3784),
    .din12(W_63_V_32_load_reg_3784),
    .din13(W_63_V_32_load_reg_3784),
    .din14(W_63_V_32_load_reg_3784),
    .din15(W_63_V_32_load_reg_3784),
    .din16(W_15_V_load_reg_2908),
    .din17(W_15_V_1_load_reg_2917),
    .din18(W_15_V_2_load_reg_2926),
    .din19(W_15_V_3_load_reg_2935),
    .din20(W_15_V_4_load_reg_2944),
    .din21(W_15_V_5_load_reg_2953),
    .din22(W_15_V_6_load_reg_2962),
    .din23(W_15_V_7_load_reg_2971),
    .din24(W_15_V_8_load_reg_2980),
    .din25(W_15_V_9_load_reg_2990),
    .din26(W_15_V_10_load_reg_3000),
    .din27(W_15_V_11_load_reg_3010),
    .din28(W_15_V_12_load_reg_3020),
    .din29(W_15_V_13_load_reg_3030),
    .din30(W_15_V_14_load_reg_3043),
    .din31(W_63_V_load_reg_3352),
    .din32(W_63_V_1_load_reg_3365),
    .din33(W_63_V_2_load_reg_3378),
    .din34(W_63_V_3_load_reg_3391),
    .din35(W_63_V_4_load_reg_3404),
    .din36(W_63_V_5_load_reg_3417),
    .din37(W_63_V_6_load_reg_3430),
    .din38(W_63_V_7_load_reg_3443),
    .din39(W_63_V_8_load_reg_3456),
    .din40(W_63_V_9_load_reg_3469),
    .din41(W_63_V_10_load_reg_3482),
    .din42(W_63_V_11_load_reg_3495),
    .din43(W_63_V_12_load_reg_3508),
    .din44(W_63_V_13_load_reg_3521),
    .din45(W_63_V_14_load_reg_3534),
    .din46(W_63_V_15_load_reg_3547),
    .din47(W_63_V_16_load_reg_3560),
    .din48(W_63_V_17_load_reg_3573),
    .din49(W_63_V_18_load_reg_3586),
    .din50(W_63_V_19_load_reg_3599),
    .din51(W_63_V_20_load_reg_3612),
    .din52(W_63_V_21_load_reg_3625),
    .din53(W_63_V_22_load_reg_3638),
    .din54(W_63_V_23_load_reg_3651),
    .din55(W_63_V_24_load_reg_3664),
    .din56(W_63_V_25_load_reg_3677),
    .din57(W_63_V_26_load_reg_3690),
    .din58(W_63_V_27_load_reg_3703),
    .din59(W_63_V_28_load_reg_3716),
    .din60(W_63_V_29_load_reg_3729),
    .din61(W_63_V_30_load_reg_3742),
    .din62(W_63_V_31_load_reg_3755),
    .din63(W_63_V_32_load_reg_3784),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln_fu_1354_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U4(
    .din0(W_63_V_45_fu_538),
    .din1(W_63_V_45_fu_538),
    .din2(W_63_V_45_fu_538),
    .din3(W_63_V_45_fu_538),
    .din4(W_63_V_45_fu_538),
    .din5(W_63_V_45_fu_538),
    .din6(W_63_V_45_fu_538),
    .din7(W_63_V_45_fu_538),
    .din8(W_63_V_45_fu_538),
    .din9(W_63_V_45_fu_538),
    .din10(W_63_V_45_fu_538),
    .din11(W_63_V_45_fu_538),
    .din12(W_63_V_45_fu_538),
    .din13(W_63_V_45_fu_538),
    .din14(W_63_V_45_fu_538),
    .din15(W_63_V_45_fu_538),
    .din16(W_15_V_13_load_reg_3030),
    .din17(W_15_V_14_load_reg_3043),
    .din18(W_63_V_load_reg_3352),
    .din19(W_63_V_1_load_reg_3365),
    .din20(W_63_V_2_load_reg_3378),
    .din21(W_63_V_3_load_reg_3391),
    .din22(W_63_V_4_load_reg_3404),
    .din23(W_63_V_5_load_reg_3417),
    .din24(W_63_V_6_load_reg_3430),
    .din25(W_63_V_7_load_reg_3443),
    .din26(W_63_V_8_load_reg_3456),
    .din27(W_63_V_9_load_reg_3469),
    .din28(W_63_V_10_load_reg_3482),
    .din29(W_63_V_11_load_reg_3495),
    .din30(W_63_V_12_load_reg_3508),
    .din31(W_63_V_13_load_reg_3521),
    .din32(W_63_V_14_load_reg_3534),
    .din33(W_63_V_15_load_reg_3547),
    .din34(W_63_V_16_load_reg_3560),
    .din35(W_63_V_17_load_reg_3573),
    .din36(W_63_V_18_load_reg_3586),
    .din37(W_63_V_19_load_reg_3599),
    .din38(W_63_V_20_load_reg_3612),
    .din39(W_63_V_21_load_reg_3625),
    .din40(W_63_V_22_load_reg_3638),
    .din41(W_63_V_23_load_reg_3651),
    .din42(W_63_V_24_load_reg_3664),
    .din43(W_63_V_25_load_reg_3677),
    .din44(W_63_V_26_load_reg_3690),
    .din45(W_63_V_27_load_reg_3703),
    .din46(W_63_V_28_load_reg_3716),
    .din47(W_63_V_29_load_reg_3729),
    .din48(W_63_V_30_load_reg_3742),
    .din49(W_63_V_31_load_reg_3755),
    .din50(W_63_V_32_load_reg_3784),
    .din51(W_63_V_33_fu_490),
    .din52(W_63_V_34_fu_494),
    .din53(W_63_V_35_fu_498),
    .din54(W_63_V_36_fu_502),
    .din55(W_63_V_37_fu_506),
    .din56(W_63_V_38_fu_510),
    .din57(W_63_V_39_fu_514),
    .din58(W_63_V_40_fu_518),
    .din59(W_63_V_41_fu_522),
    .din60(W_63_V_42_fu_526),
    .din61(W_63_V_43_fu_530),
    .din62(W_63_V_44_fu_534),
    .din63(W_63_V_45_fu_538),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln1_fu_1449_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U5(
    .din0(W_63_V_45_fu_538),
    .din1(W_63_V_45_fu_538),
    .din2(W_63_V_45_fu_538),
    .din3(W_63_V_45_fu_538),
    .din4(W_63_V_45_fu_538),
    .din5(W_63_V_45_fu_538),
    .din6(W_63_V_45_fu_538),
    .din7(W_63_V_45_fu_538),
    .din8(W_63_V_45_fu_538),
    .din9(W_63_V_45_fu_538),
    .din10(W_63_V_45_fu_538),
    .din11(W_63_V_45_fu_538),
    .din12(W_63_V_45_fu_538),
    .din13(W_63_V_45_fu_538),
    .din14(W_63_V_45_fu_538),
    .din15(W_63_V_45_fu_538),
    .din16(W_15_V_13_load_reg_3030),
    .din17(W_15_V_14_load_reg_3043),
    .din18(W_63_V_load_reg_3352),
    .din19(W_63_V_1_load_reg_3365),
    .din20(W_63_V_2_load_reg_3378),
    .din21(W_63_V_3_load_reg_3391),
    .din22(W_63_V_4_load_reg_3404),
    .din23(W_63_V_5_load_reg_3417),
    .din24(W_63_V_6_load_reg_3430),
    .din25(W_63_V_7_load_reg_3443),
    .din26(W_63_V_8_load_reg_3456),
    .din27(W_63_V_9_load_reg_3469),
    .din28(W_63_V_10_load_reg_3482),
    .din29(W_63_V_11_load_reg_3495),
    .din30(W_63_V_12_load_reg_3508),
    .din31(W_63_V_13_load_reg_3521),
    .din32(W_63_V_14_load_reg_3534),
    .din33(W_63_V_15_load_reg_3547),
    .din34(W_63_V_16_load_reg_3560),
    .din35(W_63_V_17_load_reg_3573),
    .din36(W_63_V_18_load_reg_3586),
    .din37(W_63_V_19_load_reg_3599),
    .din38(W_63_V_20_load_reg_3612),
    .din39(W_63_V_21_load_reg_3625),
    .din40(W_63_V_22_load_reg_3638),
    .din41(W_63_V_23_load_reg_3651),
    .din42(W_63_V_24_load_reg_3664),
    .din43(W_63_V_25_load_reg_3677),
    .din44(W_63_V_26_load_reg_3690),
    .din45(W_63_V_27_load_reg_3703),
    .din46(W_63_V_28_load_reg_3716),
    .din47(W_63_V_29_load_reg_3729),
    .din48(W_63_V_30_load_reg_3742),
    .din49(W_63_V_31_load_reg_3755),
    .din50(W_63_V_32_load_reg_3784),
    .din51(W_63_V_33_fu_490),
    .din52(W_63_V_34_fu_494),
    .din53(W_63_V_35_fu_498),
    .din54(W_63_V_36_fu_502),
    .din55(W_63_V_37_fu_506),
    .din56(W_63_V_38_fu_510),
    .din57(W_63_V_39_fu_514),
    .din58(W_63_V_40_fu_518),
    .din59(W_63_V_41_fu_522),
    .din60(W_63_V_42_fu_526),
    .din61(W_63_V_43_fu_530),
    .din62(W_63_V_44_fu_534),
    .din63(W_63_V_45_fu_538),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln21_1_fu_1569_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U6(
    .din0(W_63_V_45_fu_538),
    .din1(W_63_V_45_fu_538),
    .din2(W_63_V_45_fu_538),
    .din3(W_63_V_45_fu_538),
    .din4(W_63_V_45_fu_538),
    .din5(W_63_V_45_fu_538),
    .din6(W_63_V_45_fu_538),
    .din7(W_63_V_45_fu_538),
    .din8(W_63_V_45_fu_538),
    .din9(W_63_V_45_fu_538),
    .din10(W_63_V_45_fu_538),
    .din11(W_63_V_45_fu_538),
    .din12(W_63_V_45_fu_538),
    .din13(W_63_V_45_fu_538),
    .din14(W_63_V_45_fu_538),
    .din15(W_63_V_45_fu_538),
    .din16(W_15_V_13_load_reg_3030),
    .din17(W_15_V_14_load_reg_3043),
    .din18(W_63_V_load_reg_3352),
    .din19(W_63_V_1_load_reg_3365),
    .din20(W_63_V_2_load_reg_3378),
    .din21(W_63_V_3_load_reg_3391),
    .din22(W_63_V_4_load_reg_3404),
    .din23(W_63_V_5_load_reg_3417),
    .din24(W_63_V_6_load_reg_3430),
    .din25(W_63_V_7_load_reg_3443),
    .din26(W_63_V_8_load_reg_3456),
    .din27(W_63_V_9_load_reg_3469),
    .din28(W_63_V_10_load_reg_3482),
    .din29(W_63_V_11_load_reg_3495),
    .din30(W_63_V_12_load_reg_3508),
    .din31(W_63_V_13_load_reg_3521),
    .din32(W_63_V_14_load_reg_3534),
    .din33(W_63_V_15_load_reg_3547),
    .din34(W_63_V_16_load_reg_3560),
    .din35(W_63_V_17_load_reg_3573),
    .din36(W_63_V_18_load_reg_3586),
    .din37(W_63_V_19_load_reg_3599),
    .din38(W_63_V_20_load_reg_3612),
    .din39(W_63_V_21_load_reg_3625),
    .din40(W_63_V_22_load_reg_3638),
    .din41(W_63_V_23_load_reg_3651),
    .din42(W_63_V_24_load_reg_3664),
    .din43(W_63_V_25_load_reg_3677),
    .din44(W_63_V_26_load_reg_3690),
    .din45(W_63_V_27_load_reg_3703),
    .din46(W_63_V_28_load_reg_3716),
    .din47(W_63_V_29_load_reg_3729),
    .din48(W_63_V_30_load_reg_3742),
    .din49(W_63_V_31_load_reg_3755),
    .din50(W_63_V_32_load_reg_3784),
    .din51(W_63_V_33_fu_490),
    .din52(W_63_V_34_fu_494),
    .din53(W_63_V_35_fu_498),
    .din54(W_63_V_36_fu_502),
    .din55(W_63_V_37_fu_506),
    .din56(W_63_V_38_fu_510),
    .din57(W_63_V_39_fu_514),
    .din58(W_63_V_40_fu_518),
    .din59(W_63_V_41_fu_522),
    .din60(W_63_V_42_fu_526),
    .din61(W_63_V_43_fu_530),
    .din62(W_63_V_44_fu_534),
    .din63(W_63_V_45_fu_538),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln1503_1_fu_1689_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U7(
    .din0(W_63_V_31_load_reg_3755),
    .din1(W_63_V_31_load_reg_3755),
    .din2(W_63_V_31_load_reg_3755),
    .din3(W_63_V_31_load_reg_3755),
    .din4(W_63_V_31_load_reg_3755),
    .din5(W_63_V_31_load_reg_3755),
    .din6(W_63_V_31_load_reg_3755),
    .din7(W_63_V_31_load_reg_3755),
    .din8(W_63_V_31_load_reg_3755),
    .din9(W_63_V_31_load_reg_3755),
    .din10(W_63_V_31_load_reg_3755),
    .din11(W_63_V_31_load_reg_3755),
    .din12(W_63_V_31_load_reg_3755),
    .din13(W_63_V_31_load_reg_3755),
    .din14(W_63_V_31_load_reg_3755),
    .din15(W_63_V_31_load_reg_3755),
    .din16(W_15_V_15_fu_354),
    .din17(W_15_V_load_reg_2908),
    .din18(W_15_V_1_load_reg_2917),
    .din19(W_15_V_2_load_reg_2926),
    .din20(W_15_V_3_load_reg_2935),
    .din21(W_15_V_4_load_reg_2944),
    .din22(W_15_V_5_load_reg_2953),
    .din23(W_15_V_6_load_reg_2962),
    .din24(W_15_V_7_load_reg_2971),
    .din25(W_15_V_8_load_reg_2980),
    .din26(W_15_V_9_load_reg_2990),
    .din27(W_15_V_10_load_reg_3000),
    .din28(W_15_V_11_load_reg_3010),
    .din29(W_15_V_12_load_reg_3020),
    .din30(W_15_V_13_load_reg_3030),
    .din31(W_15_V_14_load_reg_3043),
    .din32(W_63_V_load_reg_3352),
    .din33(W_63_V_1_load_reg_3365),
    .din34(W_63_V_2_load_reg_3378),
    .din35(W_63_V_3_load_reg_3391),
    .din36(W_63_V_4_load_reg_3404),
    .din37(W_63_V_5_load_reg_3417),
    .din38(W_63_V_6_load_reg_3430),
    .din39(W_63_V_7_load_reg_3443),
    .din40(W_63_V_8_load_reg_3456),
    .din41(W_63_V_9_load_reg_3469),
    .din42(W_63_V_10_load_reg_3482),
    .din43(W_63_V_11_load_reg_3495),
    .din44(W_63_V_12_load_reg_3508),
    .din45(W_63_V_13_load_reg_3521),
    .din46(W_63_V_14_load_reg_3534),
    .din47(W_63_V_15_load_reg_3547),
    .din48(W_63_V_16_load_reg_3560),
    .din49(W_63_V_17_load_reg_3573),
    .din50(W_63_V_18_load_reg_3586),
    .din51(W_63_V_19_load_reg_3599),
    .din52(W_63_V_20_load_reg_3612),
    .din53(W_63_V_21_load_reg_3625),
    .din54(W_63_V_22_load_reg_3638),
    .din55(W_63_V_23_load_reg_3651),
    .din56(W_63_V_24_load_reg_3664),
    .din57(W_63_V_25_load_reg_3677),
    .din58(W_63_V_26_load_reg_3690),
    .din59(W_63_V_27_load_reg_3703),
    .din60(W_63_V_28_load_reg_3716),
    .din61(W_63_V_29_load_reg_3729),
    .din62(W_63_V_30_load_reg_3742),
    .din63(W_63_V_31_load_reg_3755),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln2_fu_1813_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U8(
    .din0(W_63_V_40_fu_518),
    .din1(W_63_V_40_fu_518),
    .din2(W_63_V_40_fu_518),
    .din3(W_63_V_40_fu_518),
    .din4(W_63_V_40_fu_518),
    .din5(W_63_V_40_fu_518),
    .din6(W_63_V_40_fu_518),
    .din7(W_63_V_40_fu_518),
    .din8(W_63_V_40_fu_518),
    .din9(W_63_V_40_fu_518),
    .din10(W_63_V_40_fu_518),
    .din11(W_63_V_40_fu_518),
    .din12(W_63_V_40_fu_518),
    .din13(W_63_V_40_fu_518),
    .din14(W_63_V_40_fu_518),
    .din15(W_63_V_40_fu_518),
    .din16(W_15_V_8_load_reg_2980),
    .din17(W_15_V_9_load_reg_2990),
    .din18(W_15_V_10_load_reg_3000),
    .din19(W_15_V_11_load_reg_3010),
    .din20(W_15_V_12_load_reg_3020),
    .din21(W_15_V_13_load_reg_3030),
    .din22(W_15_V_14_load_reg_3043),
    .din23(W_63_V_load_reg_3352),
    .din24(W_63_V_1_load_reg_3365),
    .din25(W_63_V_2_load_reg_3378),
    .din26(W_63_V_3_load_reg_3391),
    .din27(W_63_V_4_load_reg_3404),
    .din28(W_63_V_5_load_reg_3417),
    .din29(W_63_V_6_load_reg_3430),
    .din30(W_63_V_7_load_reg_3443),
    .din31(W_63_V_8_load_reg_3456),
    .din32(W_63_V_9_load_reg_3469),
    .din33(W_63_V_10_load_reg_3482),
    .din34(W_63_V_11_load_reg_3495),
    .din35(W_63_V_12_load_reg_3508),
    .din36(W_63_V_13_load_reg_3521),
    .din37(W_63_V_14_load_reg_3534),
    .din38(W_63_V_15_load_reg_3547),
    .din39(W_63_V_16_load_reg_3560),
    .din40(W_63_V_17_load_reg_3573),
    .din41(W_63_V_18_load_reg_3586),
    .din42(W_63_V_19_load_reg_3599),
    .din43(W_63_V_20_load_reg_3612),
    .din44(W_63_V_21_load_reg_3625),
    .din45(W_63_V_22_load_reg_3638),
    .din46(W_63_V_23_load_reg_3651),
    .din47(W_63_V_24_load_reg_3664),
    .din48(W_63_V_25_load_reg_3677),
    .din49(W_63_V_26_load_reg_3690),
    .din50(W_63_V_27_load_reg_3703),
    .din51(W_63_V_28_load_reg_3716),
    .din52(W_63_V_29_load_reg_3729),
    .din53(W_63_V_30_load_reg_3742),
    .din54(W_63_V_31_load_reg_3755),
    .din55(W_63_V_32_load_reg_3784),
    .din56(W_63_V_33_fu_490),
    .din57(W_63_V_34_fu_494),
    .din58(W_63_V_35_fu_498),
    .din59(W_63_V_36_fu_502),
    .din60(W_63_V_37_fu_506),
    .din61(W_63_V_38_fu_510),
    .din62(W_63_V_39_fu_514),
    .din63(W_63_V_40_fu_518),
    .din64(trunc_ln20_reg_3831),
    .dout(phi_ln215_1_fu_1883_p66)
);

sha256_core_mux_6cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sha256_core_mux_6cud_U9(
    .din0(W_15_V_15_fu_354),
    .din1(W_15_V_load_reg_2908),
    .din2(W_15_V_1_load_reg_2917),
    .din3(W_15_V_2_load_reg_2926),
    .din4(W_15_V_3_load_reg_2935),
    .din5(W_15_V_4_load_reg_2944),
    .din6(W_15_V_5_load_reg_2953),
    .din7(W_15_V_6_load_reg_2962),
    .din8(W_15_V_7_load_reg_2971),
    .din9(W_15_V_8_load_reg_2980),
    .din10(W_15_V_9_load_reg_2990),
    .din11(W_15_V_10_load_reg_3000),
    .din12(W_15_V_11_load_reg_3010),
    .din13(W_15_V_12_load_reg_3020),
    .din14(W_15_V_13_load_reg_3030),
    .din15(W_15_V_14_load_reg_3043),
    .din16(W_63_V_load_reg_3352),
    .din17(W_63_V_1_load_reg_3365),
    .din18(W_63_V_2_load_reg_3378),
    .din19(W_63_V_3_load_reg_3391),
    .din20(W_63_V_4_load_reg_3404),
    .din21(W_63_V_5_load_reg_3417),
    .din22(W_63_V_6_load_reg_3430),
    .din23(W_63_V_7_load_reg_3443),
    .din24(W_63_V_8_load_reg_3456),
    .din25(W_63_V_9_load_reg_3469),
    .din26(W_63_V_10_load_reg_3482),
    .din27(W_63_V_11_load_reg_3495),
    .din28(W_63_V_12_load_reg_3508),
    .din29(W_63_V_13_load_reg_3521),
    .din30(W_63_V_14_load_reg_3534),
    .din31(W_63_V_15_load_reg_3547),
    .din32(W_63_V_16_load_reg_3560),
    .din33(W_63_V_17_load_reg_3573),
    .din34(W_63_V_18_load_reg_3586),
    .din35(W_63_V_19_load_reg_3599),
    .din36(W_63_V_20_load_reg_3612),
    .din37(W_63_V_21_load_reg_3625),
    .din38(W_63_V_22_load_reg_3638),
    .din39(W_63_V_23_load_reg_3651),
    .din40(W_63_V_24_load_reg_3664),
    .din41(W_63_V_25_load_reg_3677),
    .din42(W_63_V_26_load_reg_3690),
    .din43(W_63_V_27_load_reg_3703),
    .din44(W_63_V_28_load_reg_3716),
    .din45(W_63_V_29_load_reg_3729),
    .din46(W_63_V_30_load_reg_3742),
    .din47(W_63_V_31_load_reg_3755),
    .din48(W_63_V_32_load_reg_3784),
    .din49(W_63_V_33_fu_490),
    .din50(W_63_V_34_fu_494),
    .din51(W_63_V_35_fu_498),
    .din52(W_63_V_36_fu_502),
    .din53(W_63_V_37_fu_506),
    .din54(W_63_V_38_fu_510),
    .din55(W_63_V_39_fu_514),
    .din56(W_63_V_40_fu_518),
    .din57(W_63_V_41_fu_522),
    .din58(W_63_V_42_fu_526),
    .din59(W_63_V_43_fu_530),
    .din60(W_63_V_44_fu_534),
    .din61(W_63_V_45_fu_538),
    .din62(W_63_V_46_fu_542),
    .din63(W_63_V_47_fu_546),
    .din64(tmp_1_fu_2369_p65),
    .dout(tmp_1_fu_2369_p66)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_0_preg <= add_ln700_fu_2491_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_1_preg <= add_ln700_1_fu_2496_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_2_preg <= add_ln700_2_fu_2501_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_3_preg <= add_ln700_3_fu_2506_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_4_preg <= add_ln700_4_fu_2511_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_5_preg <= add_ln700_5_fu_2516_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_6_preg <= add_ln700_6_fu_2521_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 32'd0;
    end else begin
        if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_return_7_preg <= add_ln700_7_fu_2526_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln14_fu_1014_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_reg_718 <= 7'd16;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i1_0_reg_718 <= i_2_fu_2234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i2_0_reg_916 <= 7'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i2_0_reg_916 <= i_1_reg_3850;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_707 <= i_reg_3059;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_707 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        lhs_V_9_reg_831 <= state_0_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        lhs_V_9_reg_831 <= a_V_fu_2679_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        lhs_V_reg_874 <= state_4_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        lhs_V_reg_874 <= e_V_fu_2667_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0478_0_reg_906 <= state_7_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_0478_0_reg_906 <= rhs_V_13_reg_895;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0535_0_reg_863 <= state_3_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        p_0535_0_reg_863 <= rhs_V_15_reg_852;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd16))) begin
            phi_ln20_reg_730 <= W_15_V_load_reg_2908;
        end else if ((1'b1 == ap_condition_533)) begin
            phi_ln20_reg_730 <= W_63_V_32_fu_486;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd62))) begin
            phi_ln20_reg_730 <= W_63_V_31_fu_482;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd61))) begin
            phi_ln20_reg_730 <= W_63_V_30_fu_478;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd60))) begin
            phi_ln20_reg_730 <= W_63_V_29_fu_474;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd59))) begin
            phi_ln20_reg_730 <= W_63_V_28_fu_470;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd58))) begin
            phi_ln20_reg_730 <= W_63_V_27_fu_466;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd57))) begin
            phi_ln20_reg_730 <= W_63_V_26_fu_462;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd56))) begin
            phi_ln20_reg_730 <= W_63_V_25_fu_458;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd55))) begin
            phi_ln20_reg_730 <= W_63_V_24_fu_454;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd54))) begin
            phi_ln20_reg_730 <= W_63_V_23_fu_450;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd53))) begin
            phi_ln20_reg_730 <= W_63_V_22_fu_446;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd52))) begin
            phi_ln20_reg_730 <= W_63_V_21_fu_442;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd51))) begin
            phi_ln20_reg_730 <= W_63_V_20_fu_438;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd50))) begin
            phi_ln20_reg_730 <= W_63_V_19_fu_434;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd49))) begin
            phi_ln20_reg_730 <= W_63_V_18_fu_430;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd48))) begin
            phi_ln20_reg_730 <= W_63_V_17_fu_426;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd47))) begin
            phi_ln20_reg_730 <= W_63_V_16_fu_422;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd46))) begin
            phi_ln20_reg_730 <= W_63_V_15_fu_418;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd45))) begin
            phi_ln20_reg_730 <= W_63_V_14_fu_414;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd44))) begin
            phi_ln20_reg_730 <= W_63_V_13_fu_410;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd43))) begin
            phi_ln20_reg_730 <= W_63_V_12_fu_406;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd42))) begin
            phi_ln20_reg_730 <= W_63_V_11_fu_402;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd41))) begin
            phi_ln20_reg_730 <= W_63_V_10_fu_398;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd40))) begin
            phi_ln20_reg_730 <= W_63_V_9_fu_394;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd39))) begin
            phi_ln20_reg_730 <= W_63_V_8_fu_390;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd38))) begin
            phi_ln20_reg_730 <= W_63_V_7_fu_386;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd37))) begin
            phi_ln20_reg_730 <= W_63_V_6_fu_382;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd36))) begin
            phi_ln20_reg_730 <= W_63_V_5_fu_378;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd35))) begin
            phi_ln20_reg_730 <= W_63_V_4_fu_374;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd34))) begin
            phi_ln20_reg_730 <= W_63_V_3_fu_370;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd33))) begin
            phi_ln20_reg_730 <= W_63_V_2_fu_366;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd32))) begin
            phi_ln20_reg_730 <= W_63_V_1_fu_362;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd31))) begin
            phi_ln20_reg_730 <= W_63_V_fu_358;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd30))) begin
            phi_ln20_reg_730 <= W_15_V_14_load_reg_3043;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd29))) begin
            phi_ln20_reg_730 <= W_15_V_13_load_reg_3030;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd28))) begin
            phi_ln20_reg_730 <= W_15_V_12_load_reg_3020;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd27))) begin
            phi_ln20_reg_730 <= W_15_V_11_load_reg_3010;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd26))) begin
            phi_ln20_reg_730 <= W_15_V_10_load_reg_3000;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd25))) begin
            phi_ln20_reg_730 <= W_15_V_9_load_reg_2990;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd24))) begin
            phi_ln20_reg_730 <= W_15_V_8_load_reg_2980;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd23))) begin
            phi_ln20_reg_730 <= W_15_V_7_load_reg_2971;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd22))) begin
            phi_ln20_reg_730 <= W_15_V_6_load_reg_2962;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd21))) begin
            phi_ln20_reg_730 <= W_15_V_5_load_reg_2953;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd20))) begin
            phi_ln20_reg_730 <= W_15_V_4_load_reg_2944;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd19))) begin
            phi_ln20_reg_730 <= W_15_V_3_load_reg_2935;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd18))) begin
            phi_ln20_reg_730 <= W_15_V_2_load_reg_2926;
        end else if (((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd17))) begin
            phi_ln20_reg_730 <= W_15_V_1_load_reg_2917;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        rhs_V_13_reg_895 <= state_6_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rhs_V_13_reg_895 <= rhs_V_reg_884;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        rhs_V_14_reg_841 <= state_1_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rhs_V_14_reg_841 <= lhs_V_9_reg_831;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        rhs_V_15_reg_852 <= state_2_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rhs_V_15_reg_852 <= rhs_V_14_reg_841;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        rhs_V_reg_884 <= state_5_V_read;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rhs_V_reg_884 <= lhs_V_reg_874;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd11) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_10_fu_334 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        W_15_V_10_load_reg_3000 <= W_15_V_10_fu_334;
        W_15_V_11_load_reg_3010 <= W_15_V_11_fu_338;
        W_15_V_12_load_reg_3020 <= W_15_V_12_fu_342;
        W_15_V_13_load_reg_3030 <= W_15_V_13_fu_346;
        W_15_V_14_load_reg_3043 <= W_15_V_14_fu_350;
        W_15_V_1_load_reg_2917 <= W_15_V_1_fu_298;
        W_15_V_2_load_reg_2926 <= W_15_V_2_fu_302;
        W_15_V_3_load_reg_2935 <= W_15_V_3_fu_306;
        W_15_V_4_load_reg_2944 <= W_15_V_4_fu_310;
        W_15_V_5_load_reg_2953 <= W_15_V_5_fu_314;
        W_15_V_6_load_reg_2962 <= W_15_V_6_fu_318;
        W_15_V_7_load_reg_2971 <= W_15_V_7_fu_322;
        W_15_V_8_load_reg_2980 <= W_15_V_8_fu_326;
        W_15_V_9_load_reg_2990 <= W_15_V_9_fu_330;
        W_15_V_load_reg_2908 <= W_15_V_fu_294;
        i_reg_3059 <= i_fu_1020_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd12) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_11_fu_338 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd13) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_12_fu_342 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd14) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_13_fu_346 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if ((~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd0) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd14) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd13) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd12) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd11) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd10) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd9) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd8) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd7) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd6) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd5) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd4) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd3) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd2) & ~(ap_phi_mux_i_0_phi_fu_711_p4 == 5'd1) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_14_fu_350 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd0) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_15_fu_354 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd2) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_1_fu_298 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd3) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_2_fu_302 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd4) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_3_fu_306 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd5) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_4_fu_310 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd6) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_5_fu_314 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd7) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_6_fu_318 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd8) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_7_fu_322 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd9) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_8_fu_326 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd10) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_9_fu_330 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_0_phi_fu_711_p4 == 5'd1) & (icmp_ln14_fu_1014_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        W_15_V_fu_294 <= W_0_V_fu_1030_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd26) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_10_fu_398 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        W_63_V_10_load_reg_3482 <= W_63_V_10_fu_398;
        W_63_V_11_load_reg_3495 <= W_63_V_11_fu_402;
        W_63_V_12_load_reg_3508 <= W_63_V_12_fu_406;
        W_63_V_13_load_reg_3521 <= W_63_V_13_fu_410;
        W_63_V_14_load_reg_3534 <= W_63_V_14_fu_414;
        W_63_V_15_load_reg_3547 <= W_63_V_15_fu_418;
        W_63_V_16_load_reg_3560 <= W_63_V_16_fu_422;
        W_63_V_17_load_reg_3573 <= W_63_V_17_fu_426;
        W_63_V_18_load_reg_3586 <= W_63_V_18_fu_430;
        W_63_V_19_load_reg_3599 <= W_63_V_19_fu_434;
        W_63_V_1_load_reg_3365 <= W_63_V_1_fu_362;
        W_63_V_20_load_reg_3612 <= W_63_V_20_fu_438;
        W_63_V_21_load_reg_3625 <= W_63_V_21_fu_442;
        W_63_V_22_load_reg_3638 <= W_63_V_22_fu_446;
        W_63_V_23_load_reg_3651 <= W_63_V_23_fu_450;
        W_63_V_24_load_reg_3664 <= W_63_V_24_fu_454;
        W_63_V_25_load_reg_3677 <= W_63_V_25_fu_458;
        W_63_V_26_load_reg_3690 <= W_63_V_26_fu_462;
        W_63_V_27_load_reg_3703 <= W_63_V_27_fu_466;
        W_63_V_28_load_reg_3716 <= W_63_V_28_fu_470;
        W_63_V_29_load_reg_3729 <= W_63_V_29_fu_474;
        W_63_V_2_load_reg_3378 <= W_63_V_2_fu_366;
        W_63_V_30_load_reg_3742 <= W_63_V_30_fu_478;
        W_63_V_31_load_reg_3755 <= W_63_V_31_fu_482;
        W_63_V_32_load_reg_3784 <= W_63_V_32_fu_486;
        W_63_V_3_load_reg_3391 <= W_63_V_3_fu_370;
        W_63_V_4_load_reg_3404 <= W_63_V_4_fu_374;
        W_63_V_5_load_reg_3417 <= W_63_V_5_fu_378;
        W_63_V_6_load_reg_3430 <= W_63_V_6_fu_382;
        W_63_V_7_load_reg_3443 <= W_63_V_7_fu_386;
        W_63_V_8_load_reg_3456 <= W_63_V_8_fu_390;
        W_63_V_9_load_reg_3469 <= W_63_V_9_fu_394;
        W_63_V_load_reg_3352 <= W_63_V_fu_358;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd27) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_11_fu_402 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd28) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_12_fu_406 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd29) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_13_fu_410 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd30) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_14_fu_414 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd31) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_15_fu_418 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd32) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_16_fu_422 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd33) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_17_fu_426 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd34) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_18_fu_430 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd35) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_19_fu_434 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd17) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_1_fu_362 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd36) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_20_fu_438 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd37) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_21_fu_442 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd38) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_22_fu_446 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd39) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_23_fu_450 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd40) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_24_fu_454 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd41) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_25_fu_458 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd42) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_26_fu_462 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd43) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_27_fu_466 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd44) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_28_fu_470 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd45) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_29_fu_474 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd18) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_2_fu_366 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd46) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_30_fu_478 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd47) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_31_fu_482 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd48) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_32_fu_486 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd49) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_33_fu_490 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd50) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_34_fu_494 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd51) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_35_fu_498 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd52) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_36_fu_502 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd53) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_37_fu_506 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd54) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_38_fu_510 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd55) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_39_fu_514 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd19) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_3_fu_370 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd56) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_40_fu_518 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd57) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_41_fu_522 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd58) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_42_fu_526 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd59) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_43_fu_530 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd60) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_44_fu_534 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd61) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_45_fu_538 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd62) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_46_fu_542 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((trunc_ln20_reg_3831 == 6'd0) | ((trunc_ln20_reg_3831 == 6'd1) | ((trunc_ln20_reg_3831 == 6'd2) | ((trunc_ln20_reg_3831 == 6'd3) | ((trunc_ln20_reg_3831 == 6'd4) | ((trunc_ln20_reg_3831 == 6'd5) | ((trunc_ln20_reg_3831 == 6'd6) | ((trunc_ln20_reg_3831 == 6'd7) | ((trunc_ln20_reg_3831 == 6'd8) | ((trunc_ln20_reg_3831 == 6'd9) | ((trunc_ln20_reg_3831 == 6'd10) | ((trunc_ln20_reg_3831 == 6'd11) | ((trunc_ln20_reg_3831 == 6'd12) | ((trunc_ln20_reg_3831 == 6'd13) | ((trunc_ln20_reg_3831 == 6'd14) | ((trunc_ln20_reg_3831 == 6'd15) | (trunc_ln20_reg_3831 == 6'd63))))))))))))))))))) begin
        W_63_V_47_fu_546 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd20) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_4_fu_374 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd21) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_5_fu_378 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd22) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_6_fu_382 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd23) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_7_fu_386 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd24) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_8_fu_390 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd25) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_9_fu_394 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln20_reg_3831 == 6'd16) & (1'b1 == ap_CS_fsm_state5))) begin
        W_63_V_fu_358 <= W_16_V_fu_1988_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        add_ln209_2_reg_3865 <= add_ln209_2_fu_2461_p2;
        ret_V_28_reg_3855 <= ret_V_28_fu_2354_p2;
        ret_V_35_reg_3870 <= ret_V_35_fu_2485_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_1_reg_3850 <= i_1_fu_2246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln18_fu_1231_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln20_reg_3831 <= trunc_ln20_fu_1237_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        K_ce0 = 1'b1;
    end else begin
        K_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_0 = add_ln700_fu_2491_p2;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_1 = add_ln700_1_fu_2496_p2;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_2 = add_ln700_2_fu_2501_p2;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_3 = add_ln700_3_fu_2506_p2;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_4 = add_ln700_4_fu_2511_p2;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_5 = add_ln700_5_fu_2516_p2;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_6 = add_ln700_6_fu_2521_p2;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_return_7 = add_ln700_7_fu_2526_p2;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln14_fu_1014_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln18_fu_1231_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln36_fu_2240_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign K_address0 = zext_ln40_fu_2360_p1;

assign W_0_V_fu_1030_p17 = i_0_reg_707[3:0];

assign W_16_V_fu_1988_p2 = (add_ln209_7_fu_1976_p2 + add_ln209_8_fu_1982_p2);

assign a_V_fu_2679_p2 = (add_ln209_5_fu_2673_p2 + ret_V_35_reg_3870);

assign add_ln209_1_fu_2455_p2 = (p_0478_0_reg_906 + tmp_1_fu_2369_p66);

assign add_ln209_2_fu_2461_p2 = (add_ln209_1_fu_2455_p2 + ret_V_25_fu_2330_p2);

assign add_ln209_5_fu_2673_p2 = (t1_V_fu_2584_p2 + ret_V_32_fu_2661_p2);

assign add_ln209_7_fu_1976_p2 = (ret_V_21_fu_1807_p2 + phi_ln2_fu_1813_p66);

assign add_ln209_8_fu_1982_p2 = (phi_ln215_1_fu_1883_p66 + ret_V_18_fu_1443_p2);

assign add_ln209_fu_2579_p2 = (K_q0 + ret_V_28_reg_3855);

assign add_ln700_1_fu_2496_p2 = (rhs_V_14_reg_841 + state_1_V_read);

assign add_ln700_2_fu_2501_p2 = (rhs_V_15_reg_852 + state_2_V_read);

assign add_ln700_3_fu_2506_p2 = (p_0535_0_reg_863 + state_3_V_read);

assign add_ln700_4_fu_2511_p2 = (lhs_V_reg_874 + state_4_V_read);

assign add_ln700_5_fu_2516_p2 = (rhs_V_reg_884 + state_5_V_read);

assign add_ln700_6_fu_2521_p2 = (rhs_V_13_reg_895 + state_6_V_read);

assign add_ln700_7_fu_2526_p2 = (p_0478_0_reg_906 + state_7_V_read);

assign add_ln700_fu_2491_p2 = (lhs_V_9_reg_831 + state_0_V_read);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_condition_533 = ((((((((((((((((((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd15)) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd63))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd14))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd13))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd12))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd11))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd10))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd9))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd8))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd7))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd6))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd5))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd4))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd3))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd2))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd1))) | ((icmp_ln18_fu_1231_p2 == 1'd0) & (trunc_ln20_fu_1237_p1 == 6'd0)));
end

assign ap_phi_mux_i_0_phi_fu_711_p4 = i_0_reg_707;

assign e_V_fu_2667_p2 = (p_0535_0_reg_863 + t1_V_fu_2584_p2);

assign i_1_fu_2246_p2 = (i2_0_reg_916 + 7'd1);

assign i_2_fu_2234_p2 = (i1_0_reg_718 + 7'd1);

assign i_fu_1020_p2 = (i_0_reg_707 + 5'd1);

assign icmp_ln14_fu_1014_p2 = ((i_0_reg_707 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_1231_p2 = ((i1_0_reg_718 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_2240_p2 = ((i2_0_reg_916 == 7'd64) ? 1'b1 : 1'b0);

assign r_V_10_fu_1787_p4 = {{phi_ln1503_1_fu_1689_p66[31:10]}};

assign r_V_14_fu_1433_p1 = r_V_7_fu_1423_p4;

assign r_V_15_fu_1797_p1 = r_V_10_fu_1787_p4;

assign r_V_16_fu_2342_p2 = (lhs_V_reg_874 ^ 32'd4294967295);

assign r_V_1_fu_2280_p4 = {{lhs_V_reg_874[31:11]}};

assign r_V_2_fu_2302_p4 = {{lhs_V_reg_874[31:25]}};

assign r_V_3_fu_2589_p4 = {{lhs_V_9_reg_831[31:2]}};

assign r_V_4_fu_2611_p4 = {{lhs_V_9_reg_831[31:13]}};

assign r_V_5_fu_2633_p4 = {{lhs_V_9_reg_831[31:22]}};

assign r_V_6_fu_1332_p4 = {{phi_ln20_1_fu_1263_p66[31:18]}};

assign r_V_7_fu_1423_p4 = {{phi_ln_fu_1354_p66[31:3]}};

assign r_V_8_fu_1547_p4 = {{phi_ln1_fu_1449_p66[31:17]}};

assign r_V_9_fu_1667_p4 = {{phi_ln21_1_fu_1569_p66[31:19]}};

assign r_V_fu_1241_p4 = {{phi_ln20_reg_730[31:7]}};

assign r_V_s_fu_2258_p4 = {{lhs_V_reg_874[31:6]}};

assign ret_V_17_fu_1346_p3 = {{trunc_ln1503_7_fu_1342_p1}, {r_V_6_fu_1332_p4}};

assign ret_V_18_fu_1443_p2 = (xor_ln1357_7_fu_1437_p2 ^ ret_V_17_fu_1346_p3);

assign ret_V_19_fu_1561_p3 = {{trunc_ln1503_8_fu_1557_p1}, {r_V_8_fu_1547_p4}};

assign ret_V_20_fu_1681_p3 = {{trunc_ln1503_9_fu_1677_p1}, {r_V_9_fu_1667_p4}};

assign ret_V_21_fu_1807_p2 = (xor_ln1357_9_fu_1801_p2 ^ ret_V_20_fu_1681_p3);

assign ret_V_22_fu_2272_p3 = {{trunc_ln1503_fu_2268_p1}, {r_V_s_fu_2258_p4}};

assign ret_V_23_fu_2294_p3 = {{trunc_ln1503_1_fu_2290_p1}, {r_V_1_fu_2280_p4}};

assign ret_V_24_fu_2316_p3 = {{trunc_ln1503_2_fu_2312_p1}, {r_V_2_fu_2302_p4}};

assign ret_V_25_fu_2330_p2 = (xor_ln1357_fu_2324_p2 ^ ret_V_23_fu_2294_p3);

assign ret_V_26_fu_2336_p2 = (rhs_V_reg_884 & lhs_V_reg_874);

assign ret_V_27_fu_2348_p2 = (rhs_V_13_reg_895 & r_V_16_fu_2342_p2);

assign ret_V_28_fu_2354_p2 = (ret_V_27_fu_2348_p2 ^ ret_V_26_fu_2336_p2);

assign ret_V_29_fu_2603_p3 = {{trunc_ln1503_3_fu_2599_p1}, {r_V_3_fu_2589_p4}};

assign ret_V_30_fu_2625_p3 = {{trunc_ln1503_4_fu_2621_p1}, {r_V_4_fu_2611_p4}};

assign ret_V_31_fu_2647_p3 = {{trunc_ln1503_5_fu_2643_p1}, {r_V_5_fu_2633_p4}};

assign ret_V_32_fu_2661_p2 = (xor_ln1357_3_fu_2655_p2 ^ ret_V_30_fu_2625_p3);

assign ret_V_33_fu_2473_p2 = (xor_ln1357_5_fu_2467_p2 & lhs_V_9_reg_831);

assign ret_V_34_fu_2479_p2 = (rhs_V_15_reg_852 & rhs_V_14_reg_841);

assign ret_V_35_fu_2485_p2 = (ret_V_34_fu_2479_p2 ^ ret_V_33_fu_2473_p2);

assign ret_V_fu_1255_p3 = {{trunc_ln1503_6_fu_1251_p1}, {r_V_fu_1241_p4}};

assign t1_V_fu_2584_p2 = (add_ln209_2_reg_3865 + add_ln209_fu_2579_p2);

assign tmp_1_fu_2369_p65 = i2_0_reg_916[5:0];

assign trunc_ln1503_1_fu_2290_p1 = lhs_V_reg_874[10:0];

assign trunc_ln1503_2_fu_2312_p1 = lhs_V_reg_874[24:0];

assign trunc_ln1503_3_fu_2599_p1 = lhs_V_9_reg_831[1:0];

assign trunc_ln1503_4_fu_2621_p1 = lhs_V_9_reg_831[12:0];

assign trunc_ln1503_5_fu_2643_p1 = lhs_V_9_reg_831[21:0];

assign trunc_ln1503_6_fu_1251_p1 = phi_ln20_reg_730[6:0];

assign trunc_ln1503_7_fu_1342_p1 = phi_ln20_1_fu_1263_p66[17:0];

assign trunc_ln1503_8_fu_1557_p1 = phi_ln1_fu_1449_p66[16:0];

assign trunc_ln1503_9_fu_1677_p1 = phi_ln21_1_fu_1569_p66[18:0];

assign trunc_ln1503_fu_2268_p1 = lhs_V_reg_874[5:0];

assign trunc_ln20_fu_1237_p1 = i1_0_reg_718[5:0];

assign xor_ln1357_3_fu_2655_p2 = (ret_V_31_fu_2647_p3 ^ ret_V_29_fu_2603_p3);

assign xor_ln1357_5_fu_2467_p2 = (rhs_V_15_reg_852 ^ rhs_V_14_reg_841);

assign xor_ln1357_7_fu_1437_p2 = (ret_V_fu_1255_p3 ^ r_V_14_fu_1433_p1);

assign xor_ln1357_9_fu_1801_p2 = (ret_V_19_fu_1561_p3 ^ r_V_15_fu_1797_p1);

assign xor_ln1357_fu_2324_p2 = (ret_V_24_fu_2316_p3 ^ ret_V_22_fu_2272_p3);

assign zext_ln40_fu_2360_p1 = i2_0_reg_916;

endmodule //sha256_transform
